#!/usr/bin/env python3
"""Render Misaeng Book 1 (WORLD21) as a readable playable script for review by the Editor (playbook R20).

    python3 tools/ms_script_md.py docs/book2/misaeng-book1-script.md

What the player sees, in play order: narration, lines, boards (caption and the decider's lines), stills, cards,
handoffs and the clue board. Only the story file's own lines; nothing from the source.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import tk_story_w21 as m  # noqa: E402

NAMES = {"ms_jang": "Jang", "ms_jang_young": "Jang (18)", "ms_jang_child": "Jang (child)", "ms_uncle": "Uncle",
         "ms_mother": "Mother", "ms_sponsor": "Sponsor", "ms_oh": "Oh", "ms_oh_hike": "Oh",
         "ms_bujang": "Department head (Oh's boss, on the phone)", "ms_buyer": "Buyer", "ms_kangsil": "Kang (buyer's manager)",
         "ms_hr": "HR staffer", "ms_kimds": "Kim Dong-sik", "ms_glasses": "Glasses intern", "ms_ahn": "Ahn Young-yi",
         "ms_han": "Han Seok-yul", "ms_kimsh": "Kim Seok-ho", "ms_director": "Director", "ms_go": "Go",
         "ms_stevehan": "Steve Han", "ms_kimbr": "Kim Bu-ryeon", "ms_trainee": "Trainee"}


def main(out_path):
    W = m.WORLD21
    nodes = {n["key"]: n for n in W["nodes"]}
    out = ['# Misaeng, Book 1: "The First Move": playable script', "",
           "_Generated by tools/ms_script_md.py from tools/tk_story_w21.py. What the player sees, in order. Narration in "
           "italics; ▶ BOARD marks a go problem the player must solve; [STILL] a full-screen illustration; ⇒ who the "
           "player controls next. Cards are full-screen title cards._", ""]
    for sec in W["opening"]:
        if sec[0] == "scroll":
            out += ["## Opening card: " + sec[1], ""] + ["> " + p for p in sec[2]] + [""]
    for k in m._ORDER:
        n = nodes[k]
        sc = W["scenes"][n["scene"]]
        where = n.get("place", "") + (" · " + n["room"] if n.get("room") else "")
        out += ["---", "", f"## {k}: {sc['title']}  ({where})", ""]
        for g in n.get("gate", []) or []:
            out += [f"**Before this beat the player must:** {g['objective']}", ""]
        ds = n.get("dilemma")
        ds = (ds if isinstance(ds, list) else [ds]) if ds else []
        rec = n.get("record")
        rec = rec if isinstance(rec, list) else ([rec] if rec else [])
        bi = 0
        for st in sc["steps"]:
            if st[0] == "n":
                out.append(f"*{st[1]}*  ")
            elif st[0] == "say":
                out.append(f"**{NAMES.get(st[1], st[1])}:** {st[2]}  ")
            elif st[0] == "still":
                out.append(f"[STILL: {st[1]}]  ")
            elif st[0] == "scroll":
                out += ["", f"> **CARD: {st[1]}**"] + ["> " + p for p in st[2]] + [""]
            elif st[0] == "problem":
                d = ds[bi] if bi < len(ds) else None
                r = rec[bi] if bi < len(rec) else None
                kind = f"multiple choice: Cho Hunhyun's real move, Black {r}" if r else "go problem"
                if d:
                    out += ["", f"▶ **BOARD ({kind})**, caption: \"{d['q']}\"",
                            f"  - as it opens, {NAMES.get(d['who'], d['who'])} thinks: \"{d['open']}\"; on solving: \"{d['win']}\"", ""]
                bi += 1
            elif st[0] == "party":
                to = st[2]["to"] if len(st) > 2 else {}
                who = ", ".join(NAMES.get(x, x) for x in st[1])
                out.append(f"⇒ *player now controls {who}*" + (f", going to {to.get('place')}" if isinstance(to, dict) else f", starting at {to}'s spot" if to else ", in place") + "  ")
            elif st[0] == "victory":
                out.append("**[END OF BOOK 1]**")
        if k == "m21" and W.get("audit"):
            out += ["", "▶ **CLUE BOARD** (\"%s\"): the player links clue cards: " % W["audit"]["title"]
                    + "; ".join(l["q"] + " → " + l["a"] for l in W["audit"]["links"]), ""]
        out.append("")
    for sec in W["closing"]:
        if sec[0] == "scroll":
            out += ["---", "", "## Closing card: " + sec[1], ""] + ["> " + p for p in sec[2]] + [""]
    Path(out_path).write_text("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "docs/book2/misaeng-book1-script.md")
