"""Chinese for the Book 2 places' lines (labels, townsfolk, challengers, objectives).

Written by Plot for tools/tk_places_w2.py (the Places session's PLACES2), matched by
the exact English. tk_places_w2.py can do `from tk_places_w2_zh import ZH_PLACES2`.
Kept in its own file so the two sessions never edit the same file.
Matches PLACES2 at claude/plot-places 131976d (older lines kept, so either version builds); Plot updates it when lines change.
"""

ZH_PLACES2 = {
    "The farewell banquet outside the Heng Gate": "横门外饯行之宴",
    "An earthen ridge above the west road": "西路上的土冈",
    "The jeweller's": "珠宝铺",
    "A wine shop": "酒肆",
    "A teahouse": "茶馆",
    "The market go table": "市中棋桌",
    "Wang Yun's residence": "王允府",
    "The Chancellor's residence": "相府",
    "Lü Bu's quarters": "吕布府",
    "Shisun Rui's house": "士孙瑞宅",
    "Huang Wan's house": "黄琬宅",
    "Weiyang Palace": "未央宫",
    "Changle Palace (roofs only)": "长乐宫（只见屋顶）",
    "The Xuanping Gate tower": "宣平门楼",
    "The farewell banquet": "饯行之宴",
    "Lü Bu's side door": "吕布府侧门",
    "Lü Bu's gate": "吕布府门",
    "Between the red lanterns": "红灯之间",
    "Lü Bu on the ridge": "土冈上的吕布",
    "The market crossroads": "市中十字路口",
    "The street before the palace": "宫前大街",
    "The North Side Gate": "北掖门",
    "The foot of the Xuanping Gate tower": "宣平门楼下",
    "The palace steps (Lü Bu's plea, on the way to A18)": "宫阶（吕布劝王允同走，往A18途中）",
    "Lü Bu's horse, tied at the gate (A9)": "系于府前的吕布之马（A9）",
    "The spirit screen": "影壁",
    "The front hall": "前厅",
    "The maids' rooms": "婢女房",
    "The rear hall": "后堂",
    "The stores": "库房",
    "The peony pavilion": "牡丹亭",
    "The painted pavilion": "画阁",
    "The 荼蘼 trellis": "荼蘼架",
    "The covered gallery": "回廊",
    "The middle hall": "中堂",
    "Dong Zhuo's bedchamber": "董卓卧房",
    "The Phoenix Pavilion": "凤仪亭",
    "Rockery (cover beside the path)": "假山（路旁可藏身）",
    "A halberd rack": "戟架",
    "A potted plum: a niche behind it is always safe": "盆梅：其后小角落，总是安全",
    "The garden gate (Dong Zhuo runs into Li Ru, end of A9)": "园门（A9末，董卓撞上李儒）",
    "Lü Bu's hall": "吕布厅堂",
    "The stable (Red Hare)": "马厩（赤兔马）",
    "The great hall of state": "都堂",
    "The emperor's side hall": "天子偏殿",
    "Inside the North Side Gate": "北掖门内",
    "Li Ru brought in bound (A15)": "李儒被缚而来（A15）",
    "The second banquet": "第二次宴会",
    "A painted screen hiding a door": "遮门的画屏",
    "The family chest": "家中宝箱",
    "The first banquet": "初次宴会",
    "The secret room": "密室",
    "Li Su": "李肃",
    "Dong Zhuo's seat": "董卓之座",
    "A sword on the wall": "壁间宝剑",
    "The sword on the wall": "壁间宝剑",
    "The window over the pond": "临池之窗",
    "A dressing table": "妆台",
    "The window": "窗前",
    "Behind the bed": "床后",
    "Lü Bu's house (A6, after the lanterns)": "吕布宅（A6，红灯之后）",
    "The workbench": "工案",
    "The victory feast": "庆功宴",
    "The boy emperor": "少年天子",
    "The secret edict": "天子密诏",
    "“Keep to the side lanes. The middle of the avenue is the Son of Heaven's. And the Grand Preceptor's.”": "“走小巷吧。大街正中是天子走的。也是太师走的。”",
    "“Two hundred and fifty thousand of us built it. Walls as high as these. Twenty years of grain inside, they say.”": "“二十五万人筑的。城墙跟这儿一样高。听说里头屯了二十年的粮。”",
    "“They drove us west from Luoyang like geese. My house is ash, and here I sell turnips.”": "“他们把我们从洛阳赶到西边，像赶鹅一样。我家成了灰，如今在这儿卖萝卜。”",
    "“He laughed, and went on eating. I couldn't hold my chopsticks. I still can't, some days.”": "“他笑着，照吃不误。我连筷子都拿不住。到如今，有时还拿不住。”",
    "“Mother says don't look at the soldiers with the long halberds.”": "“娘说，别去看那些拿长戟的兵。”",
    "“Pearls like these, Minister? Set in gold, they'd crown a general.”": "“这样的珠子，司徒？嵌在金上，够给一位将军做冠了。”",
    "“Pearls from your own house, Minister? Then the crown will be the best thing I ever made.”": "“是司徒府上自家的珠子？那这顶冠，便是我一生最好的手艺。”",
    "“That crown was the best work of my life. I hope it went to someone worth it.”": "“那顶冠是我平生最好的活计。但愿戴它的人配得上。”",
    "“The master hasn't slept. He walks the garden and sighs.”": "“老爷一夜没睡，在园里走来走去，只是叹气。”",
    "“The Grand Preceptor receives no one today.”": "“太师今日不见客。”",
    "“In Liangzhou we ride before we walk. These Chang'an streets are too narrow for a horse to stretch.”": "“在凉州，我们先会骑马后会走路。长安这些街，窄得马都伸不开腿。”",
    "“Sit, Minister. In this city it's safer to talk about stones than people.”": "“请坐，司徒。这城里，谈棋子比谈人安稳。”",
    "“Ha. You read the board the way you read a room.”": "“哈。司徒看棋，就像看人一样准。”",
    "“Another day, Minister. The stones keep.”": "“改日吧，司徒。棋子跑不了。”",
    "“Second watch, and all's well. Keep your lantern lit, sir. The Liangzhou patrols take a dark street for a guilty one.”": "“二更天，平安无事。老爷，灯笼别灭了。凉州兵见了黑巷子，就当有鬼。”",
    "A Liangzhou officer steps out of the lane. “Out after the drum, Minister? Play me for your way home.”": "一名凉州军官从巷中闪出。“司徒，鼓都打过了还出门？跟我下一局，赢了就放你回家。”",
    "“Go on, then. I never saw you.”": "“走吧。我没见过你。”",
    "“Still out, Minister?”": "“司徒还在外头？”",
    "“They say Lady Diaochan went in the covered carriage, straight to the Grand Preceptor's.”": "“听说貂蝉小姐坐着毡车，直送进太师府了。”",
    "“The Grand Preceptor's at Meiwu. The streets breathe again.”": "“太师去郿坞了。街上总算能喘口气。”",
    "“General Lü stood on that ridge till the dust was gone. Didn't say a word.”": "“吕将军在那冈上站着，直到尘土都散尽了，一句话也没说。”",
    "“The Son of Heaven is recovered from his illness! All officials to the Weiyang Hall!”": "“天子病体痊愈！百官齐赴未央殿！”",
    "“Why are we all wearing swords to a celebration?”": "“庆贺的日子，怎么人人都带着剑？”",
    "“Sell the coat! Buy wine! The old traitor is dead!”": "“卖了衣裳！打酒去！老贼死了！”",
    "“That one's for my brother, who died on the road from Luoyang.”": "“这一脚，替我兄弟踢的。他死在洛阳西迁的路上。”",
    "“Ten thousand years! Ten thousand years!”": "“万岁！万岁！”",
    "“I held a cup today. My hand didn't shake once.”": "“今天我端了一杯酒。手一下也没抖。”",
    "“The Liangzhou men are inside! Li Meng and Wang Fang opened the gates!”": "“凉州兵进城了！李蒙、王方开了城门！”",
    "“East! Get to the Xuanping Gate, the Son of Heaven is there!”": "“往东！快去宣平门，天子在那里！”",
    "“I built his walls. Now his men burn mine.”": "“我替他筑了城墙。如今他的兵烧了我的房子。”",
    "“The Grand Preceptor spent the night with the new girl and hasn't got up.”": "“太师昨夜与新人同寝，至今还没起来。”",
    "“Walk softly near the middle hall. He throws things when he's woken.”": "“到中堂附近脚步放轻些。把他吵醒了，他会扔东西。”",
    "“The young mistress doesn't go out. The Grand Preceptor's orders.”": "“小姐不出门。这是太师的吩咐。”",
    "See the Grand Preceptor off at the Heng Gate.": "往横门外，为太师送行。",
    "Walk out into the rear garden.": "到后园中走走。",
    "Have the family pearls set into a gold crown, and send it to Lü Bu in secret.": "将家藏明珠嵌成金冠，密送吕布。",
    "Receive Lü Bu in the rear hall.": "在后堂款待吕布。",
    "Dance for the Grand Preceptor in the front hall.": "在前厅为太师献舞。",
    "Ride home down the avenue.": "沿大街骑马回府。",
    "Go to the window.": "到窗前去。",
    "Nurse the Grand Preceptor.": "服侍太师养病。",
    "Meet Lü Bu at the Phoenix Pavilion, unseen.": "避开耳目，到凤仪亭与吕布相会。",
    "Answer the Grand Preceptor in the middle hall.": "到中堂回太师的话。",
    "Find Lü Bu outside the Heng Gate.": "到横门外去寻吕布。",
    "Sound out Shisun Rui.": "密访士孙瑞。",
    "Sound out Huang Wan.": "密访黄琬。",
    "Meet in the secret room.": "到密室会合。",
    "Reach the Son of Heaven unseen.": "避开耳目，面见天子。",
    "Bring Li Su into the plan.": "说李肃入伙。",
    "Escort the Grand Preceptor to the palace.": "护送太师入宫。",
    "Escort the Grand Preceptor's carriage down the avenue to the North Side Gate, the red gatehouse at its south end.": "护送太师车驾沿大街至北掖门，即大街南头的朱红门楼。",
    "Wait at the North Side Gate.": "在北掖门等候。",
    "Walk the city.": "在城中走走。",
    "Go to the victory feast in the great hall of state.": "到都堂赴庆功宴。",
    "Go to the Son of Heaven at the Xuanping Gate.": "到宣平门去见天子。",
    "The ten-li post": "十里亭",
    "The thirty-li post": "三十里亭",
    "The hundred-li post": "百里亭",
    "Dong Zhuo's tent": "董卓帐",
    "The broken wheel": "折轮之处",
    "Wind and fog": "狂风昏雾",
    "Children singing in the fields": "田间唱歌的孩子",
    "“Thirty li to the next post, sir. Mind the ruts after the bridge.”": "“离下一个驿亭还有三十里，大人。过了桥小心车辙。”",
    "The post keeper has a board out on the bench. “Long nights out here. Sit a moment, sir.”": "亭长在长凳上摆着一副棋。“这里的夜长得很。坐一会儿吧，大人。”",
    "“The road's yours. Mind the ruts.”": "“路是你的了。小心车辙。”",
    "“Safe road, sir.”": "“一路平安，大人。”",
    "“We built it, and they sent us home with nothing but a sore back.”": "“城是我们筑的，打发我们回家时，只落得一身腰疼。”",
    "“Heads down, heads down. Don't let him see your face.”": "“低头，低头。别让他看见你的脸。”",
    "“A new carriage by noon. The Grand Preceptor says it's a sign: the new for the old.”": "“午时就换新车。太师说这是吉兆：弃旧换新。”",
    "“I can't see the horse in front of me. Where's the carriage?”": "“我连前头的马都看不见。车在哪儿？”",
    "“Children in the fields at this hour? Whose children?”": "“这时辰，田里还有孩子？谁家的孩子？”",
    "Lü Bu sleeps outside the Grand Preceptor's tent, his halberd across his knees.": "吕布睡在太师帐前，画戟横在膝上。",
    "Ride beside the Grand Preceptor's carriage.": "骑马随在太师车旁。",
    "Find the Grand Preceptor in the fog.": "在雾中找到太师。",
    "Follow the singing into the fields.": "循着歌声走进田野。",
    "Dong Zhuo's hall": "董卓之堂",
    "His mother's rooms": "其母居所",
    "Diaochan's rooms": "貂蝉居所",
    "The women's quarters": "女眷住处",
    "Gold and silk": "金银绸缎",
    "Pearls and jade": "珍珠宝玉",
    "The gate (opens for Li Su with the edict)": "坞门（李肃持诏便开）",
    "Diaochan's rooms (A15m, Lü Bu; Plot to confirm the key)": "貂蝉居所（A15m，吕布；键名待Plot确认）",
    "“Walls as thick as Chang'an's. Nothing comes through this gate he doesn't want.”": "“城墙跟长安一样厚。他不想放进来的，什么也进不了这道门。”",
    "“Twenty years of grain. ‘If I succeed I hold the empire,’ he says, ‘and if not, I grow old here.’”": "“二十年的粮。他说：‘事成，雄踞天下；不成，守此足以终老。’”",
    "“They took me from my mother's door in Chang'an. Eight hundred of us, picked like peaches.”": "“他们在长安我娘的门口把我带走。我们八百人，像摘桃子一样挑来的。”",
    "“The old lady is ninety. She says her flesh trembles. She hasn't slept in days.”": "“老夫人九十了。她说身上肉颤，好几天没合眼了。”",
    "“The gate is open. Which road goes home?”": "“门开了。哪条路回家？”",
    "“Gold, tens of thousands of jin. Silver, millions. I've stopped counting the silk.”": "“黄金几万斤，白银几百万。绸缎我已经不数了。”",
    "“Let them out. All of them. Give each a little silver for the road.”": "“放她们出去，一个不留。每人给些盘缠。”",
    "Bring the edict to Dong Zhuo in his hall.": "持诏往董卓堂上。",
    "Ride out to Meiwu and bring the edict to Dong Zhuo in his hall.": "出城往郿坞，持诏至董卓堂上。",
    "Li Jue's tent": "李傕帐",
    "Guo Si's tent": "郭汜帐",
    "Zhang Ji's tent": "张济帐",
    "Fan Chou's tent": "樊稠帐",
    "Jia Xu's tent": "贾诩帐",
    "The herders' corral": "牧人的畜栏",
    "The post-pavilion (亭)": "亭",
    "The gong height": "鸣金高地",
    "The drum height": "擂鼓高地",
    "Li Jue's camp": "李傕营",
    "The herders' village": "牧人村",
    "The walled farm": "庄堡",
    "The post town": "驿镇",
    "The road east": "东去之路",
    "The mouth of Ren Valley": "任谷口",
    "“No pardon. The envoy came back with nothing. I'm going home to my mother.”": "“求赦不得。使者空手回来了。我要回家找我娘去。”",
    "“Wang Yun? A man of the east. What does he know of Liangzhou?”": "“王允？一个东边人。他懂什么凉州？”",
    "“Then we're dead men either way. Better on horseback.”": "“那横竖都是死。死在马背上强些。”",
    "“We have a wall. Walls kept out the Qiang. Will they keep out Chang'an?”": "“我们有墙。墙挡得住羌人。挡得住长安吗？”",
    "“A man without an army is just a man on a road. I've tied up better.”": "“没兵的人，不过是路上一个人。比你强的我也绑过。”",
    "“Better die marching than in our beds.”": "“死在行军路上，强过死在床上。”",
    "Hear the envoy at Li Jue's camp.": "到李傕营中听使者回报。",
    "Spread the word in the herders' village.": "在牧人村散布消息。",
    "Spread the word at the walled farm.": "在庄堡散布消息。",
    "Win over the constable at the post town.": "说服驿镇的亭长。",
    "March east.": "向东进发。",
    "Hold the mouth of Ren Valley.": "守住任谷口。",
    # added for 131976d
    "The Heng Gate: the farewell banquet": "横门：饯行之宴",
    "The earthen ridge": "土冈",
    "Wang Yun's residence: the front hall": "王允府：前厅",
    "Wang Yun's residence: the rear hall": "王允府：后堂",
    "Wang Yun's residence: the secret room": "王允府：密室",
    "Wang Yun's rear garden": "王允府后园",
    "The Chancellor's residence: the middle hall": "相府：中堂",
    "The Chancellor's residence: the bedchamber": "相府：卧房",
    "The Chancellor's rear garden: the Phoenix Pavilion": "相府后园：凤仪亭",
    "The red lanterns on the avenue": "大街上的红灯",
    "Cai Yong's house": "蔡邕宅",
    "The Xuanping Gate": "宣平门",
    "The old steward unlocks the family chest. “The pearls your father kept, master. Whatever you need them for, I never saw.”": "老管家打开家中宝箱。“这是老太爷留下的明珠，老爷。不管您拿去做什么，老奴什么也没看见。”",
    "“The chest is locked again, master. No one will know.”": "“箱子又锁好了，老爷。没人会知道。”",
    "A runner in the Chancellor's colours steps into your path. “Minister Wang, out on foot? The Grand Preceptor likes to know who walks where.”": "一个穿相府号衣的差役拦在你面前。“王司徒，走着出门？太师喜欢知道谁在哪儿走动。”",
    "“Nothing worth reporting, then. Good day, Minister.”": "“那就没什么可报的了。司徒慢走。”",
    "The runner watches you pass, and says nothing.": "差役看着你走过，一言不发。",
    "A Flying Bear soldier lounges against the wall, dice in his fist. “Bored, old man? Play me. Lose, and you buy the wine.”": "一个飞熊军士倚着墙，手里攥着骰子。“闲得慌吧，老头儿？跟我下一局。输了，你请酒。”",
    "“Hah! The old man bites. Go on.”": "“哈！老头儿还挺厉害。走吧。”",
    "“Not again, old man. My purse can't take it.”": "“不来了，老头儿。我的钱袋受不住。”",
    "A Flying Bear patrol fills the lane to Huang Wan's gate. “Visiting late, Minister? Every lane in Chang'an answers to the Grand Preceptor.”": "一队飞熊军堵住了通往黄琬家门的巷子。“司徒这么晚还去拜访？长安每条巷子都归太师管。”",
    "“On your way, then. Quickly.”": "“那就快走吧。快些。”",
    "The patrol has moved on to the next lane.": "巡兵已去了下一条巷子。",
    "A man in a plain coat has sat by Shisun Rui's gate all morning. “A game while you wait, Minister? I have time. I have nothing but time.”": "一个穿素袍的人在士孙瑞门口坐了一上午。“司徒，等人的时候下一局？我有的是工夫。我除了工夫什么也没有。”",
    "“You play like a man with nothing to hide.”": "“司徒下棋，像是心里没藏事的人。”",
    "The man in the plain coat has gone.": "穿素袍的人已经走了。",
    "A Liangzhou officer steps out of a dark lane. “Out after the drum, Minister? Play me for your way home.”": "一名凉州军官从暗巷中闪出。“司徒，鼓都打过了还出门？跟我下一局，赢了就放你回家。”",
    "“Two hundred and fifty thousand of us built Meiwu. Walls as high as these. Twenty years of grain inside, they say.”": "“二十五万人筑的郿坞。城墙跟这儿一样高。听说里头屯了二十年的粮。”",
    "Have the family pearls set into a gold crown, and get it to Lü Bu unseen.": "将家藏明珠嵌成金冠，避开耳目送到吕布手中。",
    "Ride home past the red lanterns.": "骑马经过红灯回府。",
    "Meet Lü Bu at the Phoenix Pavilion.": "到凤仪亭与吕布相会。",
    "Call on Cai Yong.": "去拜访蔡邕。",
    "The rutted bend": "车辙纵横的弯路",
    "The open plain": "空旷的原野",
    "The night camp outside the walls": "城外夜营",
    "The roadside before the city": "入城前的路边",
    "A patrol of the Grand Preceptor's horsemen bars the road. “Rider from Chang'an! Halt, and show us what you carry.”": "一队太师的骑兵拦住了路。“长安来的骑者！站住，把你带的东西拿出来！”",
    "“An edict for the Grand Preceptor? Ride on, then, and ride fast.”": "“给太师的诏书？那快走吧，快马加鞭。”",
    "The patrol waves you through.": "巡骑挥手让你过去。",
    "“We built Meiwu, and they sent us home with nothing but a sore back.”": "“郿坞是我们筑的，打发我们回家时，只落得一身腰疼。”",
    "Ride on toward the city.": "继续往城中去。",
    "The gate of Meiwu": "郿坞坞门",
    "The treasury": "库房",
    "The granaries: twenty years of grain": "粮仓：二十年之粮",
    "The gate captain turns the edict over in his hands. “Seals can be made in Chang'an. Prove you're who you say.”": "守门的队长把诏书翻来覆去地看。“印信长安也刻得出来。证明你是你说的那个人。”",
    "“Pass, Commandant Li. Open the gate!”": "“李都尉请进。开门！”",
    "The gate stands open for you.": "坞门为你敞开着。",
    "One of Dong Zhuo's guards still holds the treasury door, spear levelled. “The Grand Preceptor's gold! Nobody touches it!”": "一个董卓的卫兵仍守着库房门，长枪平举。“太师的金子！谁也不许碰！”",
    "“…He's dead, isn't he. Take it. Take all of it.”": "“……他死了，是不是。拿去吧。全拿去吧。”",
    "The guard has thrown down his spear.": "卫兵扔下了长枪。",
    "A Flying Bear officer crouches in a side court, sword half drawn. “General Lü. I always wondered which of us was better.”": "一名飞熊军官伏在侧院，刀已半出鞘。“吕将军。我一直想知道，咱俩谁更厉害。”",
    "“So now I know.”": "“这下知道了。”",
    "The officer sits against the wall and does not look up.": "军官靠墙坐着，头也不抬。",
    "Find Diaochan.": "找到貂蝉。",
    "The post town: the pavilion": "驿镇：亭",
    "A headman sits on a stone by the road, a stick across his knees. “You're spreading tales from Chang'an. Convince me first.”": "一个乡老坐在路边石上，膝上横着一根棍子。“你们在传长安来的话。先说服我。”",
    "“…Then it's true. I'll tell the others myself.”": "“……那就是真的了。我亲自去告诉大家。”",
    "“I've told them. They're coming.”": "“我已经告诉他们了。他们都来了。”",
    "The constable stands at the pavilion, arms folded. “A man without an army is just a man on a road. I've tied up better.”": "亭长站在亭前，抱着胳膊。“没兵的人，不过是路上一个人。比你强的我也绑过。”",
    "“…That's no road gang behind you. That's Liangzhou.”": "“……你身后不是一伙路匪。那是整个凉州。”",
    "The constable has taken down his rope.": "亭长已经收起了绳子。",
    "A scout calls down from his post on the hill. “General! Lü Bu's dust on the east road. Want to know how many?”": "一个斥候在山上的哨位朝下喊。“将军！东路上有吕布的尘头。要知道有多少人吗？”",
    "“Then you know as well as I do. Ready the gongs and drums.”": "“那你和我一样清楚了。备好金鼓。”",
    "The scout watches the east road.": "斥候望着东路。",
    "Win over the post town.": "说服驿镇。",
    # added for the plan grids (claude/plot-places 331d9f9, docs/book2/places-zh-todo.md)
    "A Flying Bear officer crouches among the granaries, sword half drawn. “General Lü. I always wondered which of us was better.”": "一名飞熊军官伏在粮仓之间，刀已半出鞘。“吕将军。我一直想知道，咱俩谁更厉害。”",
    "A potted plum": "盆梅",
    "A qin with a scorched tail": "焦尾之琴",
    "A rockery": "假山",
    "Bamboo-slip books": "竹简书卷",
    "Cai Yong's go table": "蔡邕的棋桌",
    "Cai Yong's study": "蔡邕书房",
    "Changle Palace": "长乐宫",
    "Lü Bu's horse, tied at the gate": "系于府前的吕布之马",
    "Lü Bu's house": "吕布宅",
    "One of Dong Zhuo's guards still holds the treasury doors, spear levelled. “The Grand Preceptor's gold! Nobody touches it!”": "一个董卓的卫兵仍守着库房大门，长枪平举。“太师的金子！谁也不许碰！”",
    "The garden gate": "园门",
    "The gate court": "门庭",
    "The palace steps": "宫阶",
    "The stable": "马厩",
    "The treasury: gold and silk": "库房：金银绸缎",
    "The treasury: pearls and jade": "库房：珍珠宝玉",
    "“Minister Wang, so far from the court? The Grand Preceptor will want to hear of it.”": "“王司徒，离朝堂这么远？太师会想知道的。”",
    "“Minister Wang? Out with a parcel? The Grand Preceptor likes to know what his ministers carry.”": "“王司徒？带着包裹出门？太师喜欢知道他的大臣们带着什么。”",
    "“Mistress? You've lost your way. The Grand Preceptor likes to know where you are.”": "“小姐？您走错路了。太师喜欢知道您在哪儿。”",
    "“The garden is cold this hour, mistress. Let me walk you back.”": "“这时辰园里凉，小姐。我送您回去吧。”",
    "“The road's yours. Mind the ruts after the bridge.”": "“路是你的了。过了桥小心车辙。”",
    # the door refusal (claude/plot-places 485d1f2)
    "The gatekeeper bars the way. “The Grand Preceptor receives no one today.”": "门吏拦住去路。“太师今日不见客。”",
    "The gatekeeper shakes his head. “The Grand Preceptor has gone back to Meiwu.”": "门吏摇头道：“太师已回郿坞去了。”",
    # the Xuanping tower stair refusal (claude/plot-places 4c4ff83)
    "The guards at the stair cross their halberds. “No one goes up to the Son of Heaven's tower.”": "楼梯口的卫士交叉画戟。“天子之楼，任何人不得上去。”",
    # a7c and a18p objectives (claude/plot-places 6cdf152)
    "Show yourself to Lü Bu behind the curtain, where the Grand Preceptor can't see.": "在帘后让吕布看见你，别让太师看见。",
    "Go to the palace steps.": "到宫阶去。",
    # the procession leash line and the a7c label (Integration's wording)
    "Li Su must keep near the Grand Preceptor.": "李肃须紧随太师车驾。",
    "Behind the curtain": "帘后",
    # shut roads (claude/plot-places dc30e3a)
    "The long road west runs on to Liangzhou. There's no errand for you there.": "西去的长路通往凉州。那边没有你的差事。",
    "Not yet. Lü Bu holds the road east. The mouth of Ren Valley comes first.": "还不行。吕布扼住东路。先到任谷口。",
    # Chang'an objectives with directions (proposed to Places after the user's playtest)
    "See the Grand Preceptor off: out through the Heng Gate, at the north end of the avenue, to the banquet tent.": "为太师送行：出大街北头的横门，到宴帐去。",
    "Go home to your residence, on the ward street just west of the avenue, and walk out into the rear garden.": "回大街西侧坊街上的府邸，到后园中走走。",
    "Take the crown to Lü Bu's side door, at the east end of the ward street, past the Chancellor's gate.": "将金冠送到坊街东头吕布府的侧门，须经过相府门前。",
    "Take the crown to Lü Bu's gate, with the weapon rack, at the east end of the ward street, past the Chancellor's gate.": "将金冠送到坊街东头吕布府门前（门边有兵器架），须经过相府门前。",
    "Ride home down the avenue, between the red lanterns.": "沿大街骑马回府，经过两行红灯。",
    "Find Lü Bu on the earthen ridge above the west road, outside the Heng Gate.": "出横门，到西路上方的土冈寻吕布。",
    "Sound out Shisun Rui, at the west end of the ward street, on the south side.": "密访士孙瑞，宅在坊街西头南侧。",
    "Sound out Huang Wan, next door to Shisun Rui.": "密访黄琬，宅在士孙瑞隔壁。",
    "Call on Cai Yong, across the avenue from Huang Wan, near the palace steps.": "去拜访蔡邕，宅在大街东侧、与黄琬隔街相对，近宫阶。",
    "Return to the secret room in your residence.": "回府中密室。",
    "Reach the Son of Heaven unseen: into the palace by the North Side Gate, at the south end of the avenue.": "避开耳目面见天子：从大街南头的北掖门入宫。",
    "Wait at the North Side Gate, at the south end of the avenue.": "在大街南头的北掖门等候。",
    "Go to the victory feast in the great hall of state, inside the palace.": "到宫中都堂赴庆功宴。",
    "Go to the palace steps, beside the North Side Gate.": "到北掖门旁的宫阶去。",
    "Go to the Son of Heaven at the Xuanping Gate, at the east end of the market street.": "到市街东头的宣平门去见天子。",
    # the legibility pass (claude/plot-places c232ced)
    "The market tower": "市楼",
    # a12a, reworded for the palace-terrace lane (claude/plot-places f0b4816)
    "Sound out Shisun Rui, on the lane at the foot of the palace terrace, at its west end.": "密访士孙瑞，宅在宫台脚下小巷的西头。",
    # a15m objective
    "Go to Meiwu.": "前往郿坞。",
    # the teahouse and the scholar's study behind it
    "The tea counter": "茶柜",
    "The back room": "后间",
    "The scholar's desk": "学士的书桌",
    "Bookshelves": "书架",
    "A go board on a low table": "矮几上的棋盘",
    "“Tea, sir? The spring leaves came up from Shu this week.”": "“客官喝茶？这礼拜的春茶刚从蜀中运到。”",
    "“Thirty years I've drunk tea in this room. Chancellors come and go; the tea stays the same.”": "“我在这屋里喝了三十年茶。相国换了一个又一个，茶还是这个味。”",
    "“The back room? Some scholar rents it. Writes all day and hardly says a word.”": "“后间？租给一位学士了。整天写字，难得说一句话。”",
    "The scholar is lost in his scrolls.": "学士埋首书卷之中。",
    "Her mirror stand": "她的镜台",
    # the Cao Cao arc (docs/book2/caocao-places-lines.md)
    "Luoyang": "洛阳",
    "The banquet in the Wenming Garden": "温明园宴席",
    "He Jin's residence": "何进府",
    "Wang Yun's house": "王允宅",
    "The Jiade Gate": "嘉德门",
    "The tower of Yong'an Palace": "永安宫楼",
    "Cao Cao's lodging": "曹操寓所",
    "Market stalls": "市集摊位",
    "A go table in the market": "市中棋桌",
    "Before the Jiade Gate": "嘉德门前",
    "The Wenming Garden banquet": "温明园之宴",
    "The street under Dong Zhuo": "董卓治下的街市",
    "The East Gate": "东门",
    "Yuan Shao's seal of office, hanging on the East Gate": "袁绍的符节，悬于东门",
    "The north gate is shut. The whole city waits on He Jin.": "北门已闭。满城都在等何进的动静。",
    "Outside the walls is no place for a colonel today. He Jin's council is sitting.": "今日不是校尉出城的时候。何进府中正在议事。",
    "Not now. The council is sitting at He Jin's.": "现在不行。何进府中正在议事。",
    "The gates are barred. The Emperor is somewhere inside the burning palace.": "城门已闩。天子还在火海般的宫中某处。",
    "Xiliang horsemen hold the north gate. No one leaves without Dong Zhuo's word.": "西凉铁骑把守北门。没有董卓的话，谁也出不去。",
    "Xiliang horsemen hold the East Gate. No one leaves without Dong Zhuo's word.": "西凉铁骑把守东门。没有董卓的话，谁也出不去。",
    "Not that way. East, out of the city, before they think to send for you.": "不是那边。往东出城，趁他们还没想起来派人找你。",
    "The East Gate is ahead. Ride up to it as if you had every right.": "东门就在前面。大大方方地骑过去，仿佛理所当然。",
    "Your face is on every gate in Luoyang now. East, and keep going.": "如今洛阳每座城门都挂着你的画像。往东，不要停。",
    "Cuihua Tower": "翠花楼",
    "The Jiade Hall": "嘉德殿",
    "The Secretariat": "省台",
    "A palace storehouse": "宫中库房",
    "By Cuihua Tower": "翠花楼前",
    "The palace gallery": "宫中阁下",
    "Inside the Jiade Gate": "嘉德门内",
    "The throne": "御座",
    "Lü Bu's armoured men": "吕布的甲士",
    "The Secretariat banquet": "省台之宴",
    "He Jin's seat": "何进之座",
    "He Jin's council": "何进府议事",
    "Where the Seven-Star Sword is kept": "七星宝刀藏处",
    "Wang Yun's \"birthday\"": "王允的“寿宴”",
    "The Chancellor's hall": "相府正堂",
    "The small pavilion": "小阁",
    "The stables": "马厩",
    "Where Lü Bu brings the horse": "吕布牵马来处",
    "Inside the Chancellor's gate": "相府门内",
    "The couch where he lies down": "他躺卧的床榻",
    "The dressing mirror": "衣镜",
    "“Xiliang horsemen ride down the middle of the street. You step aside or you're ridden down.”": "“西凉兵马当街驰过。不让开，就被踏死。”",
    "“Zheng Tai went, and Lu Zhi went. A man with a family stays, and bows, and says nothing.”": "“郑泰走了，卢植也走了。有家小的人只能留下，低头，不说话。”",
    "“The old emperor sits in the tower of Yong'an Palace. They say he wrote a poem about two swallows.”": "“旧天子住在永安宫的楼上。听说他写了一首诗，说的是两只燕子。”",
    "“The Prince of Hongnong is dead. They don't say how. No one asks.”": "“弘农王死了。没说怎么死的。也没人敢问。”",
    "“Carts came in from Yangcheng with heads hung under them. ‘Bandits,’ they said. It was market day there.”": "“车从阳城回来，车下挂着人头。说是‘贼’。那天阳城正赶社。”",
    "“The Jiade Gate is shut. The general went in to see the Empress, and he's not come out.”": "“嘉德门关了。大将军进去见太后，到现在还没出来。”",
    "“The Ten Attendants and He Jin both want the court. Whoever wins, we pay.”": "“十常侍要朝廷，何进也要朝廷。不管谁赢，遭殃的都是我们。”",
    "Go to He Jin's residence, on the main street west of the palace. The council is already sitting.": "前往何进府，在宫城西边的大街上。众官已在议事。",
    "Go to the Jiade Gate of the palace, at the north side of the main street.": "前往宫城的嘉德门，在大街北侧。",
    "Get through the burning palace to Cuihua Tower, at its north-west corner.": "穿过起火的宫城，到西北角的翠花楼。",
    "Go to the banquet in the Wenming Garden, beside the palace.": "前往宫城旁温明园的宴席。",
    "Go to the Secretariat, in the palace behind the Qingsuo Gate.": "前往省台，在青琐门内的宫中。",
    "Go to the Jiade Hall, in the palace behind the Qingsuo Gate.": "前往嘉德殿，在青琐门内的宫中。",
    "Walk the main street east towards the gate.": "沿大街往东，朝城门走。",
    "Go to the gallery in the palace, east of the inner court.": "前往宫中阁下，在内庭东边。",
    "Go to Wang Yun's house, on the main street beside He Jin's.": "前往王允宅，在大街上何进府隔壁。",
    "Go to the Chancellor's residence, south of the palace, and find him in the small pavilion.": "前往宫城南边的相府，到小阁中见董卓。",
    "Ride for the East Gate, at the end of the main street.": "驰向东门，就在大街尽头。",
    "A eunuch's guardsman bars the Qingsuo Gate, blade out, smoke pouring past him. “No one goes in! The Attendants' orders!”": "一名宦官的卫士拦在青琐门前，刀已出鞘，浓烟从他身边涌过。“谁也不许进！常侍有令！”",
    "“…The Attendants are fled. Go in, then. Find him.”": "“……常侍们都逃了。进去吧，去找他。”",
    "The guardsman has thrown down his blade and gone.": "卫士已弃刀而去。",
    "A man with an armful of palace silk backs out of the storehouse. “Everyone's taking something. Want to stop me? Play me for it.”": "一个人抱着满怀宫中绸缎从库房退出来。“人人都在拿。你想拦我？跟我下一局。”",
    "“…Fine. Fine! It's back on the shelf.”": "“……好吧，好吧！放回架上就是。”",
    "The silk is back on the shelf.": "绸缎已放回架上。",
    "A Xiliang horseman wheels in front of you. “Colonel Cao. The Chancellor's man, now? Prove you can think as well as bow.”": "一名西凉骑兵勒马挡在你面前。“曹校尉。如今也是相国的人了？证明你不光会鞠躬，也会动脑子。”",
    "“Huh. Not a fool, then.”": "“哼。倒不是个蠢人。”",
    "The horseman rides on down the middle of the street.": "骑兵沿着街心驰去。",
    "An old official sits at the market go table in a plain robe. “I resigned with Lu Zhi. Sit, Colonel, and tell me with stones why you didn't.”": "一位穿着素袍的老官坐在市中棋桌旁。“我随卢植辞了官。坐吧，校尉，用棋子告诉我，你为什么没走。”",
    "“…So you have a plan of your own. Good. Don't tell me.”": "“……原来你自有打算。好。不必告诉我。”",
    "“Go on, Colonel. Whatever you mean to do, do it well.”": "“去吧，校尉。不管你要做什么，做好它。”",
    "Beimang": "北邙山",
    "Cui Yi's farm": "崔毅庄",
    "Cui Yi's haystack": "崔毅庄的草堆",
    "A barn": "谷仓",
    "Hiding in the reeds": "藏身芦苇中",
    "The road back to the capital": "回京之路",
    "Not in the dark, with Zhang Rang's men still out. Find somewhere to hide.": "黑夜里不行，张让的人还在外面。先找个地方藏身。",
    "Follow the fireflies up from the river to a farm.": "跟着流萤，从河边往上，走到一座庄院。",
    "Go out to the road back to the capital, south of the farm.": "走到庄南回京的路上。",
    "The Camps": "营寨",
    "Ding Yuan's tent": "丁原帐",
    "Lü Bu's tent": "吕布帐",
    "Dong Zhuo's stables": "董卓马厩",
    "The paymaster's tent": "支应帐",
    "The field between the camps": "两营之间的原野",
    "Lü Bu's halberd": "吕布的画戟",
    "Ding Yuan's desk": "丁原的书案",
    "The candle": "烛",
    "The stable master": "马夫",
    "“Red Hare. A thousand li a day, and he bites.”": "“赤兔。日行千里，还会咬人。”",
    "The stable master brings out a horse red as coals, and puts the halter in your hand. “Mind his teeth.”": "马夫牵出一匹赤如炭火的马，把缰绳交到你手里。“当心它的牙。”",
    "“Red Hare's gone, then. The stall looks empty without him.”": "“赤兔牵走了。没了它，马棚都显得空了。”",
    "The paymaster": "支应官",
    "“Nothing goes out of here without the Lord's seal.”": "“没有主公的印信，这里一文也不出。”",
    "The paymaster counts out a thousand taels of gold, a few dozen bright pearls and a jade belt, and makes you sign for each.": "支应官点出黄金一千两、明珠数十颗、玉带一条，每样都要你画押。",
    "“A thousand taels, signed for. I hope he's worth it.”": "“一千两，已画押。但愿他值这个价。”",
    "“The young general rides in front. No one in the Xiliang army can stand against him.”": "“那少年将军冲在最前面。西凉军中没人挡得住他。”",
    "“Thirty li we fell back. One man did that. One man and a halberd.”": "“退了三十里。就一个人。一个人，一杆戟。”",
    "Go to Dong Zhuo's tent.": "前往董卓帐中。",
    "Collect the gifts: Red Hare from the stables, the gold from the paymaster.": "收齐礼物：到马厩牵赤兔，到支应帐取金珠。",
    "Take the gifts to Lü Bu's tent, in Ding Yuan's camp to the west.": "把礼物送到西边丁原营中的吕布帐。",
    "Go to Ding Yuan's tent.": "前往丁原帐。",
    "Pickets lying in ambush by the road spring up and surround you. “Who rides to General Lü's camp with a horse like that?”": "路旁埋伏的军人一跃而起，把你围住。“牵着这样一匹马，往吕将军营里去的是什么人？”",
    "“…An old friend of the general's. Pass, then.”": "“……原来是将军的故人。过去吧。”",
    "The pickets wave you through.": "伏路军人挥手放行。",
    "One of Ding Yuan's scouts reins in beside you. “Xiliang colours, and gifts. What does Dong Zhuo want with us?”": "丁原的一名探马勒马到你身旁。“打着西凉的旗号，还带着礼物。董卓想跟我们怎样？”",
    "“…Peace, then. I hope so.”": "“……是求和吧。但愿如此。”",
    "The scout rides back to watch the road.": "探马回去守望大路。",
    "The East Road": "东路",
    "A post station": "驿站",
    "A wanted portrait: “a thousand gold and a marquisate”": "悬赏画像：“赏千金，封万户侯”",
    "The ferryman's hut": "渡口船夫的小屋",
    "The same portrait, nailed up again": "同一张画像，又钉在这里",
    "Zhongmou county jail": "中牟县狱",
    "The pass at Zhongmou": "中牟关",
    "The stocks": "木枷",
    "The magistrate's table": "县令的案桌",
    "The back courtyard of the jail": "县狱后院",
    "Your portrait hangs on every gate of Luoyang. There's no going back.": "洛阳每座城门都挂着你的画像。已经回不去了。",
    "Zhongmou's pass is shut to a man with your face. Get through it first.": "中牟关对长着你这张脸的人是关着的。先过了这一关。",
    "Not back. East, to your father's country.": "不回头。往东，回乡里去。",
    "“They say he tried to kill the Chancellor with a jewelled sword. A thousand gold for him, and a marquisate.”": "“听说他拿一口宝刀要刺相国。拿住他赏千金，封万户侯。”",
    "“Our magistrate came from Dongjun. He keeps his own counsel.”": "“我们县令是东郡人。心里有主意，从不多说。”",
    "Ride on east to the pass at Zhongmou.": "往东骑到中牟关。",
    "The jail's back courtyard.": "县狱后院。",
    "The post-station guard holds up the portrait and looks from it to you. “Your name, and your business on this road.”": "驿站卫兵举起画像，看看画像又看看你。“报上姓名，在这条路上做什么？”",
    "“…No. He'd be older. Go on.”": "“……不对。那人该老些。走吧。”",
    "The guard is looking at someone else now.": "卫兵已在看别人了。",
    "The ferryman leans on his pole. “Crossing's a coin. Or a game, if you're short. I've seen your face somewhere, I think.”": "船夫倚着篙。“过渡一文钱。手头紧的话，下一局也行。我好像在哪里见过你这张脸。”",
    "“…No, I haven't. Get in.”": "“……没有，没见过。上船吧。”",
    "“Same price as before, sir.”": "“还是老价钱，客官。”",
    "A man with the portrait folded in his belt falls in beside you. “A thousand gold. Thinking of it makes a man sharp.”": "一个腰里折着画像的人凑到你身旁。“千金啊。一想到这个，人就机灵起来了。”",
    "“…Not sharp enough, it seems.”": "“……看来还不够机灵。”",
    "The bounty hunter studies every face that passes.": "赏金客打量着每一张过路的脸。",
    "Chenggao": "成皋",
    "Lü Boshe's front hall": "吕伯奢庄前堂",
    "The thatched rear hall": "草堂",
    "The kitchen": "厨下",
    "A roadside inn": "路边客店",
    "Behind the thatched hall": "草堂之后",
    "The road towards the west village": "往西村去的路",
    "Where Cao Cao sleeps": "曹操睡处",
    "The inn, by moonlight": "月下的客店",
    "Back towards the pass? Not with Chen Gong's post deserted behind you.": "回关上去？陈宫弃了官，身后已没有退路。",
    "It's nearly dark. Lü Boshe's farm is here, your father's sworn brother's.": "天快黑了。吕伯奢庄就在这里，是你父亲的结义兄弟。",
    "Not back. Not now.": "不能回头。现在不能。",
    "Not in the dark. The inn first.": "天黑了，不行。先去客店。",
    "East. Home.": "往东。回家。",
    "Go to Lü Boshe's farm, in the walled yard north of the road.": "前往吕伯奢庄，在大路北边的院落里。",
    "Go into the roadside inn.": "进路边客店。",
    "A woodcutter sets down his load in the deep wood. “Two riders, at dusk, off the road. Play me, and I'll forget I saw you.”": "一个樵夫在深林里放下柴担。“黄昏时两个骑马的，离了大路。跟我下一局，我就当没看见你们。”",
    "“…I never saw you. Lü Boshe's farm is just past the trees.”": "“……我谁也没看见。吕伯奢庄就在林子那头。”",
    "The woodcutter goes back to his axe.": "樵夫又拿起了斧子。",
    "Chenliu": "陈留",
    "The Cao family house": "曹家",
    "Wei Hong's mansion": "卫弘宅",
    "Grain stalls": "粮摊",
    "The white banner, 忠义": "白旗：忠义",
    "The village drilling ground": "村中校场",
    "Wei Hong's seat": "卫弘之座",
    "Wei Hong's strongbox": "卫弘的钱箱",
    "Wei Hong's banquet": "卫弘之宴",
    "Cao Song": "曹嵩",
    "“Money, son. An army eats before it fights.”": "“钱啊，儿子。军队打仗之前，先要吃饭。”",
    "“They put up a white banner. Loyalty and right. I came for the rice, and I'll stay for the banner.”": "“他们竖了一面白旗，上写忠义。我是为米来的，要为这面旗留下。”",
    "“Two thousand of us from the hills, and more coming. Is it true he went at Dong Zhuo with a sword?”": "“我们山里来了两千人，后面还有。听说他拿刀去刺董卓，是真的吗？”",
    "Go to Wei Hong's mansion, on the road east of your father's house.": "前往卫弘宅，在你父亲家东边的路上。",
    "Take Wei Hong's fortune to the drilling ground, south of the road.": "把卫弘的家资送到大路南边的校场。",
    "A volunteer swordsman blocks the recruiter's table. “I'll follow a man who can think. Show me you can.”": "一个应募的剑客拦在招兵的桌前。“我只跟会动脑子的人。你证明给我看。”",
    "“…Put my name down.”": "“……把我的名字记上。”",
    "The swordsman is drilling with the others.": "剑客正和众人一起操练。",
    "A grain merchant eyes Wei Hong's carts. “An army needs grain, and I have grain. Let's see what kind of bargainer you are.”": "一个粮商打量着卫弘的车队。“军队要粮，我有粮。看看你是什么样的买家。”",
    "“…Done. Half the price, for the banner.”": "“……成交。看在这面旗的份上，半价。”",
    "“The carts go out tomorrow, Lord Cao.”": "“车队明日出发，曹公。”",
    "Stairs up the city wall": "登城石阶",
    # Lü Bu's fall (docs/book2/lvbu-places-lines.md)
    "Xuzhou": "徐州",
    "The prefecture hall": "州衙正堂",
    "Lü Bu's lodging": "吕布寓所",
    "Liu Bei's residence": "刘备府邸",
    "Liu Bei's gate": "刘备府门",
    "The west gate, at night": "夜里的西门",
    "Under Xuzhou's wall": "徐州城下",
    "The gate is barred for the night. Someone inside must open it.": "城门已闩，入夜不开。须得城内有人开门。",
    "The gate stays shut. Up on the wall, Mi Zhu has Cao Cao's banners raised.": "城门紧闭。城上糜竺已竖起曹操的旗号。",
    "The prefect's seat": "州牧之座",
    "Cao Cao's letter": "曹操的书信",
    "The condolence call": "陈珪吊丧",
    "The hawk": "养鹰",
    "Lady Yan's rooms": "严氏内室",
    "The bride's chest": "新娘的妆奁",
    "“The Lord Liu gave Lü Bu a feast. Lord Zhang Fei didn't come, they say. Or came, and left shouting.”": "“刘使君设宴请吕布。听说张将军没来。也有人说来了，又嚷着走了。”",
    "“Cao Bao keeps the west gate. A Danyang man, and Lü Bu is his son-in-law, you know.”": "“曹豹守西门。丹阳人，吕布是他女婿，你知道吧。”",
    "“No one troubles the Lord Liu's ladies. General Lü's orders.”": "“刘使君的家眷，谁也不许打扰。吕将军的命令。”",
    "One of Zhang Fei's drinking companions sways out of the wine shop. “You're the one he calls the slave of three surnames! A game, and if you lose, you drink!”": "张飞的一个酒友摇摇晃晃走出酒肆。“你就是他说的三姓家奴！来下一局，输了就喝！”",
    "“…Hic. You play better than he says.”": "“……嗝。你下得比他说的好。”",
    "Zhang Fei's friend is asleep on the bench.": "张飞的酒友在长凳上睡着了。",
    "A Danyang soldier of Cao Bao's leans on his spear. “Our general's daughter married you, didn't she? Let's see if you're worth her.”": "曹豹手下一名丹阳兵拄着枪。“我们将军的女儿嫁给了你，是吧？看看你配不配。”",
    "“Hah. You'll do.”": "“哈。还行。”",
    "The Danyang soldier salutes.": "丹阳兵行了个礼。",
    "Go to the prefecture hall, on the main street west of the cross, where Liu Bei receives you.": "前往州衙正堂，在十字街口西边的大街上，刘备在那里迎你。",
    "Go to your lodging's rear hall, on the north side of the main street east of the cross.": "前往你寓所的后堂，在十字街口东边大街的北侧。",
    "Go to the prefecture hall: Liu Bei has something to show you.": "前往州衙正堂：刘备有东西给你看。",
    "Ride to Xuzhou's west gate in the moonlight.": "趁月色骑到徐州西门。",
    "Go to Lady Yan's rooms, in the lodging's court.": "前往严氏内室，在寓所院中。",
    "Go to the prefecture hall: Chen Gui has come to call.": "前往州衙正堂：陈珪来访。",
    "Go to the prefecture hall.": "前往州衙正堂。",
    "Ride back to Xuzhou's west gate.": "骑回徐州西门。",
    "Xiaopei": "小沛",
    "Lü Bu's halberd, planted at the camp gate": "吕布的画戟，插在辕门",
    "Xiaopei's county hall": "小沛县衙",
    "The camp gate": "辕门",
    "Where the side path meets the road": "小路与官道交会处",
    "Lü Bu's seat": "吕布之座",
    "Ji Ling's table": "纪灵之席",
    "Liu Bei's table": "刘备之席",
    "The bow and the arrows": "弓与箭",
    "“They say the general can put an arrow through a halberd's side blade at a hundred and fifty paces. I say nobody can.”": "“听说将军能在一百五十步外射中画戟小枝。我说谁也做不到。”",
    "“I saw it. Straight through the little blade. Ji Ling went home without a fight.”": "“我亲眼看见的。正中小枝。纪灵没打就回去了。”",
    "A falconer looks up from his bird. “Out hunting, Adviser? The hawk won't fly for a man in a hurry. Play me while she settles.”": "一个鹰师从鹰上抬起头。“出来打猎，先生？鹰不为心急的人飞。趁它安顿，跟我下一局。”",
    "“She'll fly for you now.”": "“这下它肯为你飞了。”",
    "The falconer's hawk is on the wing.": "鹰师的鹰飞起来了。",
    "Go to your tent in the camp, west of Xiaopei. The halberd stands at the camp gate.": "前往你在小沛西边营中的大帐。画戟插在辕门。",
    "Take the side path through the hunting ground to the road, and cut the courier off.": "穿过猎场的小路到官道上，截住驿使。",
    "The Shouchun Road": "寿春路",
    "The bridal carriage": "新娘的车驾",
    "The drums and pipes": "鼓乐",
    "The bridal party": "送亲队伍",
    "“Drums and pipes went by an hour ago, with a red carriage. A wedding for the south, they said.”": "“一个时辰前过去一队鼓乐，还有一辆红车。说是往南边成亲去的。”",
    "One of Ji Ling's outriders wheels his horse across the narrows. “The bride of the House of Yuan rides under our guard. Turn back.”": "纪灵的一名探马拨马横在隘口。“袁家的新娘由我们护送。回去。”",
    "“…Lü Bu's own man. Then go and argue with her escort, not me.”": "“……原来是吕布的人。那去跟她的护卫争吧，别找我。”",
    "The outrider has ridden back to the column.": "探马已回到队伍中。",
    "Ride the Shouchun road south after the bridal party, thirty li, and bring the bride home.": "沿寿春路往南追送亲队伍，追出三十里，把新娘带回来。",
    "Xiao Pass": "萧关",
    "Chen Gong's men's tents": "陈宫部下的营帐",
    "A watch fire": "一堆篝火",
    "Cao Cao's camp, below the pass": "关下曹操的营寨",
    "The top of the pass road": "关道顶上",
    "The cliff's edge above Cao Cao's camp": "曹营上方的崖边",
    "A Taishan bandit blocks the narrow road, a club on his shoulder. “Toll, scholar. Or a game, if you're too poor for silver.”": "一个泰山贼扛着棍子拦住窄路。“书生，留下买路钱。没银子的话，下一局也行。”",
    "“…Go on, then. I never liked Chen Gong's lot anyway.”": "“……走吧。我本来就不喜欢陈宫那伙人。”",
    "The bandit has melted back into the hills.": "贼人已隐入山中。",
    "One of Chen Gong's sentries leans on his spear by the bend. “Cold night for a walk, sir. Keep me awake a while?”": "陈宫的一名哨兵倚着枪站在弯道旁。“夜里冷，先生出来走走？陪我解解困？”",
    "“Ha. Now I'm awake.”": "“哈。这下醒了。”",
    "The sentry stamps his feet against the cold.": "哨兵跺着脚取暖。",
    "“Who goes there? Oh, Master Chen. The Adviser said no one comes up tonight.” You're sent back down the road.": "“什么人？哦，陈先生。陈公台说今夜谁也不许上来。”你被打发下山去了。",
    "Climb the pass road at night and reach the cliff's edge above Cao Cao's camp, unseen by Chen Gong's men.": "趁夜爬上关道，到曹营上方的崖边，别让陈宫的人看见。",
    "The Xiapi Road": "下邳路",
    "Xiapi in sight": "望见下邳",
    "Lü Bu keeps beside his household's carriages.": "吕布守在家眷的车驾旁。",
    "“Grain carts, all morning. Whatever's coming to Xuzhou, the general isn't staying to meet it.”": "“运粮车走了一上午。不管什么要来徐州，将军是不打算等着迎了。”",
    "Escort your household and the grain carts down the road to Xiapi.": "护送家眷和粮车，沿路前往下邳。",
    "Xiapi": "下邳",
    "Lü Bu's residence": "吕布府",
    "The granary": "粮仓",
    "The White Gate tower": "白门楼",
    "Cao Cao's siege camp": "曹操围城的营寨",
    "Liu Bei's camp": "刘备的营寨",
    "The stables' door": "马院门口",
    "Liu Bei's lines": "刘备的阵线",
    "Out of the east gate": "出东门",
    "Red Hare's saddle, ready": "赤兔马的鞍子，已备好",
    "The mirror": "铜镜",
    "The halberd": "画戟",
    "Chen Gong's plan": "陈宫之计",
    "Where Lü Bu is packing": "吕布收拾行装之处",
    "Fifty lashes": "五十背花",
    "The chair where Lü Bu dozed": "吕布打盹的椅子",
    "White flags": "白旗",
    "“Cao Cao's dug in on three sides and Liu Bei sits on the Huainan road. Nobody's getting out.”": "“曹操三面扎营，刘备守着淮南路。谁也出不去。”",
    "“The water's up to the doorsteps on the south side. The east gate's the only dry way left.”": "“南边的水已漫到门槛了。只剩东门这一条旱路。”",
    "An officer of Hou Cheng's spits in the gutter. “No wine, no pay, and the general up there with his women. Play me, General, and tell me why I should stay.”": "侯成手下一名军官往沟里啐了一口。“没酒，没饷，将军在楼上陪着妻妾。跟我下一局，将军，说说我为什么要留下。”",
    "“…Fair enough. I'll stay. For now.”": "“……也罢。我留下。暂且留下。”",
    "The officer goes back to his post, still muttering.": "军官回到岗位上，还在嘀咕。",
    "A sentry at the foot of the wall stairs stands to. “General! I've counted Cao Cao's fires all night. Shall I count them for you?”": "城墙梯下的一名哨兵立正。“将军！曹营的火我数了一夜。要我数给您听吗？”",
    "“Then you know what I know.”": "“那你知道的，我也知道了。”",
    "The sentry has gone back up the wall.": "哨兵已回到城墙上。",
    "“Who's at the horses? General Hou?” The guard peers through the rain, and you back off into the dark.": "“谁在马那边？侯将军？”守卒在雨中张望，你退回暗处。",
    "Go to your residence, on the north-west of the city, where Chen Gong waits in your hall.": "前往你的府邸，在城西北，陈宫在你堂上等候。",
    "Go from your rooms across the court to his hall, where he is packing to ride out.": "从你的内室穿过院子，到他堂上，他正收拾行装要出城。",
    "Carry your daughter out by the White Gate and down the Huainan road to Liu Bei's lines.": "背着女儿出白门，沿淮南路到刘备的阵线。",
    "Ride Red Hare round the flooded city, then back to your residence.": "骑赤兔绕行被淹的城池，再回到府中。",
    "Go to your residence.": "前往你的府邸。",
    "Take Red Hare from the stables and ride out of the dry east gate, unseen.": "从马院牵出赤兔，悄悄从无水的东门骑出城。",
    "Go up the White Gate tower.": "登上白门楼。",
    "Chen Deng's advice": "陈登献策",
    "Go to the prefecture hall: Chen Deng has advice for you.": "前往州衙正堂：陈登有话要对你说。",
    "The household's carriages, bound for Xiapi": "家眷的车驾，往下邳去",
    "Grain carts for Xiapi": "运往下邳的粮车",
    "The gate is barred, and the water stands at its arch. Only the east gate opens.": "城门已闩，水已漫到门洞。只有东门还开着。",
}
