"""Chinese for the Book 2 places' lines (labels, townsfolk, challengers, objectives).

Written by Plot for tools/tk_places_w2.py (the Places session's PLACES2), matched by
the exact English. tk_places_w2.py can do `from tk_places_w2_zh import ZH_PLACES2`.
Kept in its own file so the two sessions never edit the same file.
Matches PLACES2 at claude/plot-places 131976d (older lines kept, so either version builds); Plot updates it when lines change.
"""

ZH_PLACES2 = {
    "The farewell banquet outside the Heng Gate": "横门外饯行之宴",
    "An earthen ridge above the west road": "西路上的土冈",
    "The jeweller's": "珠宝铺",
    "A wine shop": "酒肆",
    "A teahouse": "茶馆",
    "The market go table": "市中棋桌",
    "Wang Yun's residence": "王允府",
    "The Chancellor's residence": "相府",
    "Lü Bu's quarters": "吕布府",
    "Shisun Rui's house": "士孙瑞宅",
    "Huang Wan's house": "黄琬宅",
    "Weiyang Palace": "未央宫",
    "Changle Palace (roofs only)": "长乐宫（只见屋顶）",
    "The Xuanping Gate tower": "宣平门楼",
    "The farewell banquet": "饯行之宴",
    "Lü Bu's side door": "吕布府侧门",
    "Lü Bu's gate": "吕布府门",
    "Between the red lanterns": "红灯之间",
    "Lü Bu on the ridge": "土冈上的吕布",
    "The market crossroads": "市中十字路口",
    "The street before the palace": "宫前大街",
    "The North Side Gate": "北掖门",
    "The foot of the Xuanping Gate tower": "宣平门楼下",
    "The palace steps (Lü Bu's plea, on the way to A18)": "宫阶（吕布劝王允同走，往A18途中）",
    "Lü Bu's horse, tied at the gate (A9)": "系于府前的吕布之马（A9）",
    "The spirit screen": "影壁",
    "The front hall": "前厅",
    "The maids' rooms": "婢女房",
    "The rear hall": "后堂",
    "The stores": "库房",
    "The peony pavilion": "牡丹亭",
    "The painted pavilion": "画阁",
    "The 荼蘼 trellis": "荼蘼架",
    "The covered gallery": "回廊",
    "The middle hall": "中堂",
    "Dong Zhuo's bedchamber": "董卓卧房",
    "The Phoenix Pavilion": "凤仪亭",
    "Rockery (cover beside the path)": "假山（路旁可藏身）",
    "A halberd rack": "戟架",
    "A potted plum: a niche behind it is always safe": "盆梅：其后小角落，总是安全",
    "The garden gate (Dong Zhuo runs into Li Ru, end of A9)": "园门（A9末，董卓撞上李儒）",
    "Lü Bu's hall": "吕布厅堂",
    "The stable (Red Hare)": "马厩（赤兔马）",
    "The great hall of state": "都堂",
    "The emperor's side hall": "天子偏殿",
    "Inside the North Side Gate": "北掖门内",
    "Li Ru brought in bound (A15)": "李儒被缚而来（A15）",
    "The second banquet": "第二次宴会",
    "A painted screen hiding a door": "遮门的画屏",
    "The family chest": "家中宝箱",
    "The first banquet": "初次宴会",
    "The secret room": "密室",
    "Li Su": "李肃",
    "Dong Zhuo's seat": "董卓之座",
    "A sword on the wall": "壁间宝剑",
    "The sword on the wall": "壁间宝剑",
    "The window over the pond": "临池之窗",
    "A dressing table": "妆台",
    "The window": "窗前",
    "Behind the bed": "床后",
    "Lü Bu's house (A6, after the lanterns)": "吕布宅（A6，红灯之后）",
    "The workbench": "工案",
    "The victory feast": "庆功宴",
    "The boy emperor": "少年天子",
    "The secret edict": "天子密诏",
    "“Keep to the side lanes. The middle of the avenue is the Son of Heaven's. And the Grand Preceptor's.”": "“走小巷吧。大街正中是天子走的。也是太师走的。”",
    "“Two hundred and fifty thousand of us built it. Walls as high as these. Twenty years of grain inside, they say.”": "“二十五万人筑的。城墙跟这儿一样高。听说里头屯了二十年的粮。”",
    "“They drove us west from Luoyang like geese. My house is ash, and here I sell turnips.”": "“他们把我们从洛阳赶到西边，像赶鹅一样。我家成了灰，如今在这儿卖萝卜。”",
    "“He laughed, and went on eating. I couldn't hold my chopsticks. I still can't, some days.”": "“他笑着，照吃不误。我连筷子都拿不住。到如今，有时还拿不住。”",
    "“Mother says don't look at the soldiers with the long halberds.”": "“娘说，别去看那些拿长戟的兵。”",
    "“Pearls like these, Minister? Set in gold, they'd crown a general.”": "“这样的珠子，司徒？嵌在金上，够给一位将军做冠了。”",
    "“Pearls from your own house, Minister? Then the crown will be the best thing I ever made.”": "“是司徒府上自家的珠子？那这顶冠，便是我一生最好的手艺。”",
    "“That crown was the best work of my life. I hope it went to someone worth it.”": "“那顶冠是我平生最好的活计。但愿戴它的人配得上。”",
    "“The master hasn't slept. He walks the garden and sighs.”": "“老爷一夜没睡，在园里走来走去，只是叹气。”",
    "“The Grand Preceptor receives no one today.”": "“太师今日不见客。”",
    "“In Liangzhou we ride before we walk. These Chang'an streets are too narrow for a horse to stretch.”": "“在凉州，我们先会骑马后会走路。长安这些街，窄得马都伸不开腿。”",
    "“Sit, Minister. In this city it's safer to talk about stones than people.”": "“请坐，司徒。这城里，谈棋子比谈人安稳。”",
    "“Ha. You read the board the way you read a room.”": "“哈。司徒看棋，就像看人一样准。”",
    "“Another day, Minister. The stones keep.”": "“改日吧，司徒。棋子跑不了。”",
    "“Second watch, and all's well. Keep your lantern lit, sir. The Liangzhou patrols take a dark street for a guilty one.”": "“二更天，平安无事。老爷，灯笼别灭了。凉州兵见了黑巷子，就当有鬼。”",
    "A Liangzhou officer steps out of the lane. “Out after the drum, Minister? Play me for your way home.”": "一名凉州军官从巷中闪出。“司徒，鼓都打过了还出门？跟我下一局，赢了就放你回家。”",
    "“Go on, then. I never saw you.”": "“走吧。我没见过你。”",
    "“Still out, Minister?”": "“司徒还在外头？”",
    "“They say Lady Diaochan went in the covered carriage, straight to the Grand Preceptor's.”": "“听说貂蝉小姐坐着毡车，直送进太师府了。”",
    "“The Grand Preceptor's at Meiwu. The streets breathe again.”": "“太师去郿坞了。街上总算能喘口气。”",
    "“General Lü stood on that ridge till the dust was gone. Didn't say a word.”": "“吕将军在那冈上站着，直到尘土都散尽了，一句话也没说。”",
    "“The Son of Heaven is recovered from his illness! All officials to the Weiyang Hall!”": "“天子病体痊愈！百官齐赴未央殿！”",
    "“Why are we all wearing swords to a celebration?”": "“庆贺的日子，怎么人人都带着剑？”",
    "“Sell the coat! Buy wine! The old traitor is dead!”": "“卖了衣裳！打酒去！老贼死了！”",
    "“That one's for my brother, who died on the road from Luoyang.”": "“这一脚，替我兄弟踢的。他死在洛阳西迁的路上。”",
    "“Ten thousand years! Ten thousand years!”": "“万岁！万岁！”",
    "“I held a cup today. My hand didn't shake once.”": "“今天我端了一杯酒。手一下也没抖。”",
    "“The Liangzhou men are inside! Li Meng and Wang Fang opened the gates!”": "“凉州兵进城了！李蒙、王方开了城门！”",
    "“East! Get to the Xuanping Gate, the Son of Heaven is there!”": "“往东！快去宣平门，天子在那里！”",
    "“I built his walls. Now his men burn mine.”": "“我替他筑了城墙。如今他的兵烧了我的房子。”",
    "“The Grand Preceptor spent the night with the new girl and hasn't got up.”": "“太师昨夜与新人同寝，至今还没起来。”",
    "“Walk softly near the middle hall. He throws things when he's woken.”": "“到中堂附近脚步放轻些。把他吵醒了，他会扔东西。”",
    "“The young mistress doesn't go out. The Grand Preceptor's orders.”": "“小姐不出门。这是太师的吩咐。”",
    "See the Grand Preceptor off at the Heng Gate.": "往横门外，为太师送行。",
    "Walk out into the rear garden.": "到后园中走走。",
    "Have the family pearls set into a gold crown, and send it to Lü Bu in secret.": "将家藏明珠嵌成金冠，密送吕布。",
    "Receive Lü Bu in the rear hall.": "在后堂款待吕布。",
    "Dance for the Grand Preceptor in the front hall.": "在前厅为太师献舞。",
    "Ride home down the avenue.": "沿大街骑马回府。",
    "Go to the window.": "到窗前去。",
    "Nurse the Grand Preceptor.": "服侍太师养病。",
    "Meet Lü Bu at the Phoenix Pavilion, unseen.": "避开耳目，到凤仪亭与吕布相会。",
    "Answer the Grand Preceptor in the middle hall.": "到中堂回太师的话。",
    "Find Lü Bu outside the Heng Gate.": "到横门外去寻吕布。",
    "Sound out Shisun Rui.": "密访士孙瑞。",
    "Sound out Huang Wan.": "密访黄琬。",
    "Meet in the secret room.": "到密室会合。",
    "Reach the Son of Heaven unseen.": "避开耳目，面见天子。",
    "Bring Li Su into the plan.": "说李肃入伙。",
    "Escort the Grand Preceptor to the palace.": "护送太师入宫。",
    "Wait at the North Side Gate.": "在北掖门等候。",
    "Walk the city.": "在城中走走。",
    "Go to the victory feast in the great hall of state.": "到都堂赴庆功宴。",
    "Go to the Son of Heaven at the Xuanping Gate.": "到宣平门去见天子。",
    "The ten-li post": "十里亭",
    "The thirty-li post": "三十里亭",
    "The hundred-li post": "百里亭",
    "Dong Zhuo's tent": "董卓帐",
    "The broken wheel": "折轮之处",
    "Wind and fog": "狂风昏雾",
    "Children singing in the fields": "田间唱歌的孩子",
    "“Thirty li to the next post, sir. Mind the ruts after the bridge.”": "“离下一个驿亭还有三十里，大人。过了桥小心车辙。”",
    "The post keeper has a board out on the bench. “Long nights out here. Sit a moment, sir.”": "亭长在长凳上摆着一副棋。“这里的夜长得很。坐一会儿吧，大人。”",
    "“The road's yours. Mind the ruts.”": "“路是你的了。小心车辙。”",
    "“Safe road, sir.”": "“一路平安，大人。”",
    "“We built it, and they sent us home with nothing but a sore back.”": "“城是我们筑的，打发我们回家时，只落得一身腰疼。”",
    "“Heads down, heads down. Don't let him see your face.”": "“低头，低头。别让他看见你的脸。”",
    "“A new carriage by noon. The Grand Preceptor says it's a sign: the new for the old.”": "“午时就换新车。太师说这是吉兆：弃旧换新。”",
    "“I can't see the horse in front of me. Where's the carriage?”": "“我连前头的马都看不见。车在哪儿？”",
    "“Children in the fields at this hour? Whose children?”": "“这时辰，田里还有孩子？谁家的孩子？”",
    "Lü Bu sleeps outside the Grand Preceptor's tent, his halberd across his knees.": "吕布睡在太师帐前，画戟横在膝上。",
    "Ride beside the Grand Preceptor's carriage.": "骑马随在太师车旁。",
    "Find the Grand Preceptor in the fog.": "在雾中找到太师。",
    "Follow the singing into the fields.": "循着歌声走进田野。",
    "Dong Zhuo's hall": "董卓之堂",
    "His mother's rooms": "其母居所",
    "Diaochan's rooms": "貂蝉居所",
    "The women's quarters": "女眷住处",
    "Gold and silk": "金银绸缎",
    "Pearls and jade": "珍珠宝玉",
    "The gate (opens for Li Su with the edict)": "坞门（李肃持诏便开）",
    "Diaochan's rooms (A15m, Lü Bu; Plot to confirm the key)": "貂蝉居所（A15m，吕布；键名待Plot确认）",
    "“Walls as thick as Chang'an's. Nothing comes through this gate he doesn't want.”": "“城墙跟长安一样厚。他不想放进来的，什么也进不了这道门。”",
    "“Twenty years of grain. ‘If I succeed I hold the empire,’ he says, ‘and if not, I grow old here.’”": "“二十年的粮。他说：‘事成，雄踞天下；不成，守此足以终老。’”",
    "“They took me from my mother's door in Chang'an. Eight hundred of us, picked like peaches.”": "“他们在长安我娘的门口把我带走。我们八百人，像摘桃子一样挑来的。”",
    "“The old lady is ninety. She says her flesh trembles. She hasn't slept in days.”": "“老夫人九十了。她说身上肉颤，好几天没合眼了。”",
    "“The gate is open. Which road goes home?”": "“门开了。哪条路回家？”",
    "“Gold, tens of thousands of jin. Silver, millions. I've stopped counting the silk.”": "“黄金几万斤，白银几百万。绸缎我已经不数了。”",
    "“Let them out. All of them. Give each a little silver for the road.”": "“放她们出去，一个不留。每人给些盘缠。”",
    "Bring the edict to Dong Zhuo in his hall.": "持诏往董卓堂上。",
    "Ride out to Meiwu and bring the edict to Dong Zhuo in his hall.": "出城往郿坞，持诏至董卓堂上。",
    "Li Jue's tent": "李傕帐",
    "Guo Si's tent": "郭汜帐",
    "Zhang Ji's tent": "张济帐",
    "Fan Chou's tent": "樊稠帐",
    "Jia Xu's tent": "贾诩帐",
    "The herders' corral": "牧人的畜栏",
    "The post-pavilion (亭)": "亭",
    "The gong height": "鸣金高地",
    "The drum height": "擂鼓高地",
    "Li Jue's camp": "李傕营",
    "The herders' village": "牧人村",
    "The walled farm": "庄堡",
    "The post town": "驿镇",
    "The road east": "东去之路",
    "The mouth of Ren Valley": "任谷口",
    "“No pardon. The envoy came back with nothing. I'm going home to my mother.”": "“求赦不得。使者空手回来了。我要回家找我娘去。”",
    "“Wang Yun? A man of the east. What does he know of Liangzhou?”": "“王允？一个东边人。他懂什么凉州？”",
    "“Then we're dead men either way. Better on horseback.”": "“那横竖都是死。死在马背上强些。”",
    "“We have a wall. Walls kept out the Qiang. Will they keep out Chang'an?”": "“我们有墙。墙挡得住羌人。挡得住长安吗？”",
    "“A man without an army is just a man on a road. I've tied up better.”": "“没兵的人，不过是路上一个人。比你强的我也绑过。”",
    "“Better die marching than in our beds.”": "“死在行军路上，强过死在床上。”",
    "Hear the envoy at Li Jue's camp.": "到李傕营中听使者回报。",
    "Spread the word in the herders' village.": "在牧人村散布消息。",
    "Spread the word at the walled farm.": "在庄堡散布消息。",
    "Win over the constable at the post town.": "说服驿镇的亭长。",
    "March east.": "向东进发。",
    "Hold the mouth of Ren Valley.": "守住任谷口。",
    # added for 131976d
    "The Heng Gate: the farewell banquet": "横门：饯行之宴",
    "The earthen ridge": "土冈",
    "Wang Yun's residence: the front hall": "王允府：前厅",
    "Wang Yun's residence: the rear hall": "王允府：后堂",
    "Wang Yun's residence: the secret room": "王允府：密室",
    "Wang Yun's rear garden": "王允府后园",
    "The Chancellor's residence: the middle hall": "相府：中堂",
    "The Chancellor's residence: the bedchamber": "相府：卧房",
    "The Chancellor's rear garden: the Phoenix Pavilion": "相府后园：凤仪亭",
    "The red lanterns on the avenue": "大街上的红灯",
    "Cai Yong's house": "蔡邕宅",
    "The Xuanping Gate": "宣平门",
    "The old steward unlocks the family chest. “The pearls your father kept, master. Whatever you need them for, I never saw.”": "老管家打开家中宝箱。“这是老太爷留下的明珠，老爷。不管您拿去做什么，老奴什么也没看见。”",
    "“The chest is locked again, master. No one will know.”": "“箱子又锁好了，老爷。没人会知道。”",
    "A runner in the Chancellor's colours steps into your path. “Minister Wang, out on foot? The Grand Preceptor likes to know who walks where.”": "一个穿相府号衣的差役拦在你面前。“王司徒，走着出门？太师喜欢知道谁在哪儿走动。”",
    "“Nothing worth reporting, then. Good day, Minister.”": "“那就没什么可报的了。司徒慢走。”",
    "The runner watches you pass, and says nothing.": "差役看着你走过，一言不发。",
    "A Flying Bear soldier lounges against the wall, dice in his fist. “Bored, old man? Play me. Lose, and you buy the wine.”": "一个飞熊军士倚着墙，手里攥着骰子。“闲得慌吧，老头儿？跟我下一局。输了，你请酒。”",
    "“Hah! The old man bites. Go on.”": "“哈！老头儿还挺厉害。走吧。”",
    "“Not again, old man. My purse can't take it.”": "“不来了，老头儿。我的钱袋受不住。”",
    "A Flying Bear patrol fills the lane to Huang Wan's gate. “Visiting late, Minister? Every lane in Chang'an answers to the Grand Preceptor.”": "一队飞熊军堵住了通往黄琬家门的巷子。“司徒这么晚还去拜访？长安每条巷子都归太师管。”",
    "“On your way, then. Quickly.”": "“那就快走吧。快些。”",
    "The patrol has moved on to the next lane.": "巡兵已去了下一条巷子。",
    "A man in a plain coat has sat by Shisun Rui's gate all morning. “A game while you wait, Minister? I have time. I have nothing but time.”": "一个穿素袍的人在士孙瑞门口坐了一上午。“司徒，等人的时候下一局？我有的是工夫。我除了工夫什么也没有。”",
    "“You play like a man with nothing to hide.”": "“司徒下棋，像是心里没藏事的人。”",
    "The man in the plain coat has gone.": "穿素袍的人已经走了。",
    "A Liangzhou officer steps out of a dark lane. “Out after the drum, Minister? Play me for your way home.”": "一名凉州军官从暗巷中闪出。“司徒，鼓都打过了还出门？跟我下一局，赢了就放你回家。”",
    "“Two hundred and fifty thousand of us built Meiwu. Walls as high as these. Twenty years of grain inside, they say.”": "“二十五万人筑的郿坞。城墙跟这儿一样高。听说里头屯了二十年的粮。”",
    "Have the family pearls set into a gold crown, and get it to Lü Bu unseen.": "将家藏明珠嵌成金冠，避开耳目送到吕布手中。",
    "Ride home past the red lanterns.": "骑马经过红灯回府。",
    "Meet Lü Bu at the Phoenix Pavilion.": "到凤仪亭与吕布相会。",
    "Call on Cai Yong.": "去拜访蔡邕。",
    "The rutted bend": "车辙纵横的弯路",
    "The open plain": "空旷的原野",
    "The night camp outside the walls": "城外夜营",
    "The roadside before the city": "入城前的路边",
    "A patrol of the Grand Preceptor's horsemen bars the road. “Rider from Chang'an! Halt, and show us what you carry.”": "一队太师的骑兵拦住了路。“长安来的骑者！站住，把你带的东西拿出来！”",
    "“An edict for the Grand Preceptor? Ride on, then, and ride fast.”": "“给太师的诏书？那快走吧，快马加鞭。”",
    "The patrol waves you through.": "巡骑挥手让你过去。",
    "“We built Meiwu, and they sent us home with nothing but a sore back.”": "“郿坞是我们筑的，打发我们回家时，只落得一身腰疼。”",
    "Ride on toward the city.": "继续往城中去。",
    "The gate of Meiwu": "郿坞坞门",
    "The treasury": "库房",
    "The granaries: twenty years of grain": "粮仓：二十年之粮",
    "The gate captain turns the edict over in his hands. “Seals can be made in Chang'an. Prove you're who you say.”": "守门的队长把诏书翻来覆去地看。“印信长安也刻得出来。证明你是你说的那个人。”",
    "“Pass, Commandant Li. Open the gate!”": "“李都尉请进。开门！”",
    "The gate stands open for you.": "坞门为你敞开着。",
    "One of Dong Zhuo's guards still holds the treasury door, spear levelled. “The Grand Preceptor's gold! Nobody touches it!”": "一个董卓的卫兵仍守着库房门，长枪平举。“太师的金子！谁也不许碰！”",
    "“…He's dead, isn't he. Take it. Take all of it.”": "“……他死了，是不是。拿去吧。全拿去吧。”",
    "The guard has thrown down his spear.": "卫兵扔下了长枪。",
    "A Flying Bear officer crouches in a side court, sword half drawn. “General Lü. I always wondered which of us was better.”": "一名飞熊军官伏在侧院，刀已半出鞘。“吕将军。我一直想知道，咱俩谁更厉害。”",
    "“So now I know.”": "“这下知道了。”",
    "The officer sits against the wall and does not look up.": "军官靠墙坐着，头也不抬。",
    "Find Diaochan.": "找到貂蝉。",
    "The post town: the pavilion": "驿镇：亭",
    "A headman sits on a stone by the road, a stick across his knees. “You're spreading tales from Chang'an. Convince me first.”": "一个乡老坐在路边石上，膝上横着一根棍子。“你们在传长安来的话。先说服我。”",
    "“…Then it's true. I'll tell the others myself.”": "“……那就是真的了。我亲自去告诉大家。”",
    "“I've told them. They're coming.”": "“我已经告诉他们了。他们都来了。”",
    "The constable stands at the pavilion, arms folded. “A man without an army is just a man on a road. I've tied up better.”": "亭长站在亭前，抱着胳膊。“没兵的人，不过是路上一个人。比你强的我也绑过。”",
    "“…That's no road gang behind you. That's Liangzhou.”": "“……你身后不是一伙路匪。那是整个凉州。”",
    "The constable has taken down his rope.": "亭长已经收起了绳子。",
    "A scout calls down from his post on the hill. “General! Lü Bu's dust on the east road. Want to know how many?”": "一个斥候在山上的哨位朝下喊。“将军！东路上有吕布的尘头。要知道有多少人吗？”",
    "“Then you know as well as I do. Ready the gongs and drums.”": "“那你和我一样清楚了。备好金鼓。”",
    "The scout watches the east road.": "斥候望着东路。",
    "Win over the post town.": "说服驿镇。",
    # added for the plan grids (claude/plot-places 331d9f9, docs/book2/places-zh-todo.md)
    "A Flying Bear officer crouches among the granaries, sword half drawn. “General Lü. I always wondered which of us was better.”": "一名飞熊军官伏在粮仓之间，刀已半出鞘。“吕将军。我一直想知道，咱俩谁更厉害。”",
    "A potted plum": "盆梅",
    "A qin with a scorched tail": "焦尾之琴",
    "A rockery": "假山",
    "Bamboo-slip books": "竹简书卷",
    "Cai Yong's go table": "蔡邕的棋桌",
    "Cai Yong's study": "蔡邕书房",
    "Changle Palace": "长乐宫",
    "Lü Bu's horse, tied at the gate": "系于府前的吕布之马",
    "Lü Bu's house": "吕布宅",
    "One of Dong Zhuo's guards still holds the treasury doors, spear levelled. “The Grand Preceptor's gold! Nobody touches it!”": "一个董卓的卫兵仍守着库房大门，长枪平举。“太师的金子！谁也不许碰！”",
    "The garden gate": "园门",
    "The gate court": "门庭",
    "The palace steps": "宫阶",
    "The stable": "马厩",
    "The treasury: gold and silk": "库房：金银绸缎",
    "The treasury: pearls and jade": "库房：珍珠宝玉",
    "“Minister Wang, so far from the court? The Grand Preceptor will want to hear of it.”": "“王司徒，离朝堂这么远？太师会想知道的。”",
    "“Minister Wang? Out with a parcel? The Grand Preceptor likes to know what his ministers carry.”": "“王司徒？带着包裹出门？太师喜欢知道他的大臣们带着什么。”",
    "“Mistress? You've lost your way. The Grand Preceptor likes to know where you are.”": "“小姐？您走错路了。太师喜欢知道您在哪儿。”",
    "“The garden is cold this hour, mistress. Let me walk you back.”": "“这时辰园里凉，小姐。我送您回去吧。”",
    "“The road's yours. Mind the ruts after the bridge.”": "“路是你的了。过了桥小心车辙。”",
    # the door refusal (claude/plot-places 485d1f2)
    "The gatekeeper bars the way. “The Grand Preceptor receives no one today.”": "门吏拦住去路。“太师今日不见客。”",
    "The gatekeeper shakes his head. “The Grand Preceptor has gone back to Meiwu.”": "门吏摇头道：“太师已回郿坞去了。”",
    # the Xuanping tower stair refusal (claude/plot-places 4c4ff83)
    "The guards at the stair cross their halberds. “No one goes up to the Son of Heaven's tower.”": "楼梯口的卫士交叉画戟。“天子之楼，任何人不得上去。”",
    # a7c and a18p objectives (claude/plot-places 6cdf152)
    "Show yourself to Lü Bu behind the curtain, where the Grand Preceptor can't see.": "在帘后让吕布看见你，别让太师看见。",
    "Go to the palace steps.": "到宫阶去。",
    # the procession leash line and the a7c label (Integration's wording)
    "Li Su must keep near the Grand Preceptor.": "李肃须紧随太师车驾。",
    "Behind the curtain": "帘后",
    # shut roads (claude/plot-places dc30e3a)
    "The long road west runs on to Liangzhou. There's no errand for you there.": "西去的长路通往凉州。那边没有你的差事。",
    "Not yet. Lü Bu holds the road east. The mouth of Ren Valley comes first.": "还不行。吕布扼住东路。先到任谷口。",
    # Chang'an objectives with directions (proposed to Places after the user's playtest)
    "See the Grand Preceptor off: out through the Heng Gate, at the north end of the avenue, to the banquet tent.": "为太师送行：出大街北头的横门，到宴帐去。",
    "Go home to your residence, on the ward street just west of the avenue, and walk out into the rear garden.": "回大街西侧坊街上的府邸，到后园中走走。",
    "Take the crown to Lü Bu's side door, at the east end of the ward street, past the Chancellor's gate.": "将金冠送到坊街东头吕布府的侧门，须经过相府门前。",
    "Take the crown to Lü Bu's gate, with the weapon rack, at the east end of the ward street, past the Chancellor's gate.": "将金冠送到坊街东头吕布府门前（门边有兵器架），须经过相府门前。",
    "Ride home down the avenue, between the red lanterns.": "沿大街骑马回府，经过两行红灯。",
    "Find Lü Bu on the earthen ridge above the west road, outside the Heng Gate.": "出横门，到西路上方的土冈寻吕布。",
    "Sound out Shisun Rui, at the west end of the ward street, on the south side.": "密访士孙瑞，宅在坊街西头南侧。",
    "Sound out Huang Wan, next door to Shisun Rui.": "密访黄琬，宅在士孙瑞隔壁。",
    "Call on Cai Yong, across the avenue from Huang Wan, near the palace steps.": "去拜访蔡邕，宅在大街东侧、与黄琬隔街相对，近宫阶。",
    "Return to the secret room in your residence.": "回府中密室。",
    "Reach the Son of Heaven unseen: into the palace by the North Side Gate, at the south end of the avenue.": "避开耳目面见天子：从大街南头的北掖门入宫。",
    "Wait at the North Side Gate, at the south end of the avenue.": "在大街南头的北掖门等候。",
    "Go to the victory feast in the great hall of state, inside the palace.": "到宫中都堂赴庆功宴。",
    "Go to the palace steps, beside the North Side Gate.": "到北掖门旁的宫阶去。",
    "Go to the Son of Heaven at the Xuanping Gate, at the east end of the market street.": "到市街东头的宣平门去见天子。",
    # the legibility pass (claude/plot-places c232ced)
    "The market tower": "市楼",
    # a12a, reworded for the palace-terrace lane (claude/plot-places f0b4816)
    "Sound out Shisun Rui, on the lane at the foot of the palace terrace, at its west end.": "密访士孙瑞，宅在宫台脚下小巷的西头。",
    # a15m objective
    "Go to Meiwu.": "前往郿坞。",
}
