"""Chinese for every line of the Three Kingdoms story, keyed by the English.

The voice-over reads these (tools/build_tk_voice.py). Lines that come
straight from the novel keep its wording; the rest is plain modern
Mandarin. build_tk.py refuses to build if an English line has no entry
here, so editing the story can't silently drop its voice-over.
"""

ZH = {
    # ---- inside buildings (tk_places.ROOMS) ----
    "“Wine, pork, a bed for the night — we have it all.”": "“酒、肉、过夜的床铺，小店样样都有。”",
    "“They say the governor is raising volunteers. I've half a mind to join.”": "“听说太守在招募义兵，我倒有心去投军。”",
    "“Sit, have some tea. The storyteller starts soon.”": "“坐，喝杯茶。说书的马上就开讲了。”",
    "“Another pot, and another tale of the old days.”": "“再来一壶，再听一段古。”",
    "“This is the county office. State your business.”": "“这里是县衙，有何贵干？”",
    "“Mind the floor — I've only just swept it.”": "“当心脚下，我刚扫过地。”",
    "“It isn't much, but the roof keeps the rain off.”": "“屋子虽简陋，好歹能遮风挡雨。”",
    "“The harvest is in, if the rebels don't take it.”": "“庄稼收了，只盼别被贼人抢去。”",
    "“Orders come at dawn. Keep your weapon close.”": "“军令天亮就到，兵器别离身。”",
    # interior names
    "Inn": "客栈", "Teahouse": "茶馆", "Hall": "厅堂", "House": "民居", "Hut": "茅屋", "Farmhouse": "农舍", "Tent": "营帐",
    # ---- World 1: opening ----
    "臨江仙 · The Immortal by the River": "临江仙",
    "On and on the Yangtze rolls east, its waves washing the heroes away.": "滚滚长江东逝水，浪花淘尽英雄。",
    "Right and wrong, triumph and ruin — turn your head, and all is empty.": "是非成败转头空。",
    "Yet the green hills remain, through how many crimson sunsets.": "青山依旧在，几度夕阳红。",
    "— Yang Shen": "——杨慎",
    "Chapter 1": "第一回",
    "The empire, long divided, must unite; long united, must divide.": "话说天下大势，分久必合，合久必分。",
    "The Han has ruled for four hundred years. Now Emperor Ling trusts only his eunuchs, the Ten Attendants, who sell offices and silence honest men. Omens fill the sky: a serpent coils on the throne, hens turn into cocks, black vapour drifts into the palace.":
        "汉朝传国四百年，到了灵帝，只信宦官。十常侍卖官鬻爵，陷害忠良。天下异象频生：青蛇盘踞御座，母鸡化为公鸡，黑气飞入宫殿。",
    "In Julu, a healer named Zhang Jiao preaches the Way of Great Peace. In the year 184 half a million rise behind him, yellow scarves on their heads, chanting: “The Blue Heaven is dead! The Yellow Heaven shall rise!”":
        "巨鹿人张角，传太平道，施符治病。中平元年，四五十万百姓头裹黄巾，随他造反，齐声高呼：“苍天已死，黄天当立！”",
    "The Yellow Turbans must be put down. The court sends its generals against them, and the governor of You Province posts a call for volunteers. The notice reaches Zhuo County…": "黄巾必须剿灭。朝廷遣将分三路讨之，幽州太守刘焉也出榜招募义兵。榜文传到了涿县……",
    # ---- the notice ----
    "The Notice at Zhuo": "涿县榜文",
    "Liu Bei, twenty-eight, descends from Prince Jing of Zhongshan — yet he sells sandals and weaves mats for a living. His ears reach his shoulders; his arms hang past his knees.":
        "刘备，字玄德，中山靖王之后，年二十八，家贫，以贩屦织席为业。他两耳垂肩，双手过膝。",
    "He reads the notice, and sighs.": "他看了榜文，长叹一声。",
    "A real man should serve his country! What are you sighing for?": "大丈夫不与国家出力，何故长叹？",
    "I am of the Han imperial house, Liu Bei, called Xuande. I long to crush these rebels and bring peace, but I lack the strength.": "我本汉室宗亲，姓刘，名备，字玄德。有志破贼安民，只恨力不能及，所以长叹。",
    "I'm Zhang Fei, called Yide. I've got money and land. Let's raise men together! But first, wine.": "我姓张，名飞，字翼德。我颇有些钱财，正好招募乡勇，与你同举大事！走，先喝一杯！",
    "At the village inn, a giant pushing a cart strides in: nine feet tall, a beard two feet long, a face like a ripe red date.": "村店里，一条大汉推着车子进来：身长九尺，髯长二尺，面如重枣。",
    "Wine, quickly! I'm off to the city to join the army.": "快斟酒来！我要赶进城去投军。",
    "Then sit with us, friend. We have the same purpose.": "壮士请同坐，我们志向相同。",
    "Guan Yu, called Yunchang, of Hedong. I killed a bully who preyed on my village, and I've been on the run five years.": "我姓关，名羽，字云长，河东解良人。因本处豪强欺压百姓，被我杀了，逃难江湖已有五六年。",
    # ---- the oath ----
    "The Peach Garden Oath": "桃园结义",
    "Behind my farm is a peach garden in full bloom. Tomorrow, let's swear brotherhood there before Heaven and Earth!": "我庄后有一桃园，花开正盛。明日就在园中祭告天地，我们三人结为兄弟！",
    "With a black ox and a white horse for sacrifice, the three burn incense and bow.": "次日，三人备下乌牛白马，在桃园中焚香再拜。",
    "Though we were not born on the same day of the same month of the same year…": "不求同年同月同日生……",
    "…we wish to die on the same day of the same month of the same year.": "……只愿同年同月同日死。",
    "Heaven and Earth, witness it! If we betray this oath, may Heaven and men strike us down!": "皇天后土，实鉴此心！背义忘恩，天人共戮！",
    "Liu Bei becomes eldest brother, Guan Yu second, Zhang Fei youngest. Five hundred village braves join them, and they drink in the garden until they can drink no more.":
        "刘备为兄，关羽次之，张飞为弟。乡中勇士五百余人前来投奔，众人在桃园中痛饮一醉。",
    "Their road forks here. The long road passes through the rebels' heartland; the mountain trail is shorter, and steeper.": "前路在此分岔：大路穿过黄巾腹地；山路更近，却也更险。",
    # ---- Daxing Mountain ----
    "First Blood at Daxing Mountain": "大兴山初战",
    "Traitors to the realm! Why not surrender now?": "反国逆贼，何不早降！",
    "Deng Mao — bring me his head!": "邓茂，去取他首级！",
    "Zhang Fei's spear takes Deng Mao through the heart.": "张飞挺丈八蛇矛，一枪刺中邓茂心窝。",
    "Cheng Yuanzhi charges — and Guan Yu's great blade cuts him in two. The rebels throw down their spears and run.": "程远志拍马来战，被关羽一刀挥为两段。贼众纷纷倒戈而逃。",
    # ---- Qingzhou ----
    "The Ambush at Qingzhou": "青州伏兵",
    "Rebels besiege Qingzhou. The relief force is outnumbered and falls back thirty li.": "黄巾围困青州。救兵寡不敌众，退兵三十里下寨。",
    "They are many and we are few. Only surprise will win this. Yunchang, hide your men behind the left hill. Yide, behind the right. When the gongs sound, strike.":
        "贼众我寡，必出奇兵，方可取胜。云长引兵伏于山左，翼德伏于山右，鸣金为号，一齐杀出。",
    "Next morning Liu Bei attacks — then turns and flees. The rebels chase him over the ridge.": "次日，刘备引军鼓噪而进，交战片刻便退。贼众乘势追赶，越过山岭。",
    "Gongs crash. Guan Yu and Zhang Fei burst from both flanks as Liu Bei wheels around. Caught from three sides, the rebels break, and the siege of Qingzhou is lifted.":
        "金声大作，关张两军左右齐出，刘备回军复杀。三路夹攻，贼众大溃，青州之围遂解。",
    # ---- the cage cart ----
    "The Cage Cart": "槛车",
    "Xuande! I had Zhang Jiao surrounded. But the court's envoy demanded a bribe, and I refused him. Now I go to the capital in chains, and Dong Zhuo takes my army.":
        "玄德！我围张角，眼看就要破贼。朝廷派来的使者向我索贿，我不肯给。如今我被押解进京，兵马交给了董卓。",
    "I'll cut down these guards and set him free!": "我去杀了这些押送的军士，救出卢中郎！",
    "Liu Bei looks at the cart, at the four guards, at Zhang Fei's hand on his blade.": "玄德看看囚车，看看四名军士，又看看张飞按剑的手。",
    "If I free him, I am a rebel. If I stand by, an honest man goes to his ruin.": "劫了囚车，我便是反贼；袖手旁观，忠良便要受冤。",
    "He deserves to die. But I am a sheriff, and he is the court's own man.": "此人死有余辜。可我是县尉，他是朝廷的人。",
    "It is clear to me now.": "我明白了。",
    "Not yet. Let me think it through once more.": "且慢，容我再想想。",
    "I know what I must do.": "我知道该怎么做了。",
    "Not yet. I cannot bring myself to say it.": "且慢，我实在说不出口。",
    "Free Lu Zhi, or trust the court?": "劫囚车救卢植，还是信朝廷？",
    "Kill the inspector, or spare him?": "杀督邮，还是饶他一命？",
    "After the notice, Liu Bei and Zhang Fei sit down to wine at a village inn, and talk of the Yellow Turbans.": "看过榜文，玄德与张飞来到村中酒店，对饮闲谈，说起黄巾之乱。",
    "Then a giant pushing a cart strides in: nine feet tall, a beard two feet long, a face like a ripe red date.": "正饮间，只见一条大汉推着一辆车子，到店门首歇下：身长九尺，髯长二尺，面如重枣。",
    "Who is this red-faced giant? He walks in like he owns the road.": "这红脸大汉是谁？进门来好大的气派！",
    "A man who kills a bully is no stranger at this table.": "杀了恶霸的好汉，便是自家人！",
    "Qingzhou must not fall. We go at once.": "青州不可失，即刻发兵！",
    "Gong Jing's city is besieged by the Yellow Turbans. Liu Bei marches to relieve it.": "龚景的城池被黄巾围困，玄德引兵前去解围。",
    "Zhu Jun and I have burned their camp at Changshe, and their army is broken.": "我与朱儁已火烧长社，贼军大败。",
    "Their army lost thousands in the fire, and the rest ran.": "贼军烧死无数，余众四散奔逃。",
    "Heading home, the brothers hear a roar behind the hills. Dong Zhuo, who took over Lu Zhi's army, has just been beaten by Zhang Jiao: Han troops in rout, and behind them banners reading GENERAL OF HEAVEN.": "兄弟三人回师途中，忽闻山后喊声大震：接替卢植的董卓，刚被张角杀败，官军大溃，后面旗号上写着“天公将军”。",
    "The three ride into his flank and drive him back fifty li. They bring the beaten commander, Dong Zhuo, safely back to his camp.": "三人冲入侧翼，杀退张角五十余里，护着败军之将董卓回到营中。",
    "Zhang Bao is Zhang Jiao's brother, the Yellow Turbans' General of Earth, and he is said to command sorcery: he calls up wind and thunder, and armies out of thin air. Zhu Jun's men have been broken against him once already.": "张宝是张角之弟，黄巾的“地公将军”，相传善使妖术，能呼风唤雨，撒豆成兵。朱儁的人马已被他杀败过一回。",
    "If he is not stopped, the Han line at Yangcheng will fall.": "若不制住他，阳城一线的官军便守不住了。",
    "Wind howls and thunder rolls. Out of a black cloud pours a numberless host of horsemen. They are not men: they are riders cut from paper and straw, and the spell gives them life.": "狂风大作，雷声隆隆，黑云中涌出无数人马。那些并非活人，乃是纸剪草扎的人马，被妖法唤作兵将。",
    "Liu Bei's army, seeing a host it cannot hurt, breaks and flees.": "玄德之军见敌不可伤，大败而走。",
    "Sorcery. Paper and straw wearing the shape of men; no blade can kill what was never alive. Fall back to the road.": "妖术！纸草扎成人马，本无生命，刀剑杀之不得。且退回大路。",
    "The blood of pigs, sheep and dogs. The farm east of here has all three. I will go and ask the farmers for it.": "猪、羊、狗的血，东边农庄三样都有。我去向庄户讨来。",
    "Then Yide and I take a ridge each, I the left and he the right, with a thousand men and a bucket for every man.": "那我与翼德各守一处山头，我在左，他在右，各带一千人马，人人备一桶。",
    "And when the paper horses come down, we drown them!": "纸马一下来，便泼他个落花流水！",
    "First the blood, all three. Then up to my brothers on the ridges. When the gun sounds, we strike.": "先把三样血都讨来，再送上两位兄弟的山头。号炮一响，便动手。",
    "The court will judge him fairly. Don't be rash, Yide!": "朝廷自有公论，翼德不可造次！",
    # ---- Dong Zhuo ----
    "“What Office Do You Hold?”": "现居何职",
    "Heading home, the brothers hear a roar behind the hills: Han troops in rout, and behind them banners reading GENERAL OF HEAVEN.": "三人北归途中，忽闻山后喊声大震：汉军大败，后面黄巾漫山遍野，旗上大书“天公将军”。",
    "That is Zhang Jiao! Charge!": "这是张角！快杀过去！",
    "The three ride into his flank and drive him back fifty li. They escort the defeated commander, Dong Zhuo, safely to his camp.": "三人飞马冲杀，张角大乱，败走五十余里。他们救下董卓，护送回寨。",
    "And what office do you hold?": "你们现居何职？",
    "None, my lord. We are commoners.": "白身。",
    "Dong Zhuo turns his back without a word of thanks.": "董卓甚是轻视，连谢也不谢。",
    "We bled to save that wretch and he treats us like dirt! I'll kill him!": "我们亲赴血战救了这厮，他却如此无礼！不杀他，难消我气！",
    "He is an officer of the court! You cannot.": "他是朝廷命官，岂可擅杀！",
    "That night they leave to join Zhu Jun instead, the general they met at Yingchuan. He is fighting Zhang Bao in the hills near Yangcheng.": "三人连夜引军，投奔在颍川见过的朱儁去了。朱儁正在阳城一带的山中与张宝交战。",
    # ---- black wind ----
    "Black Wind, Paper Soldiers": "黑风纸兵",
    "Zhu Jun's army faces Zhang Bao, the General of Earth. Zhang Fei spears his officer Gao Sheng from the saddle — and then Zhang Bao lets down his hair, raises his sword, and chants.":
        "朱儁进讨地公将军张宝。张飞出马，刺高升于马下。张宝随即披发仗剑，作起妖法。",
    "Wind howls and thunder rolls. Out of a black cloud pours a numberless host of horsemen. Liu Bei's army breaks and flees.": "只见风雷大作，一股黑气从天而降，黑气中似有无数人马杀来。刘备军中大乱，败阵而归。",
    "Blood breaks sorcery. Tomorrow, hide men on the hilltops with the blood of pigs, sheep and dogs. When his spirits come, drench them, and the spell will break.": "妖术怕血。明日宰杀猪羊狗，取血伏于山头，等他的神兵赶来，从高坡上泼下，其法可解。",
    # ---- boss ----
    "The General of Earth Falls": "地公将军之死",
    "Zhang Bao": "张宝", "General of Earth": "地公将军",   # the boss's name card (scenes.py)
    "Anxi": "安喜", "The posting station": "驿馆", "The Anxi county office": "安喜县衙",
    "Again Zhang Bao calls the wind. Liu Bei turns and flees, as planned, and the rebels chase him in under the ridges.": "次日，张宝又作妖法。玄德依计拨马便走，张宝驱兵赶来，正追到两边山岭之下。",
    "A signal gun — and blood and filth rain down from the ridge.": "将过山头，号炮一响，秽物齐泼。",
    "Paper men and straw horses flutter to the ground. The wind dies. Liu Bei's arrow strikes Zhang Bao in the arm, and he flees into Yangcheng.": "但见空中纸人草马纷纷坠地，风雷顿息。刘备一箭射中张宝左臂，张宝逃入阳城。",
    "Wind and thunder answer to me! Your little band will be swept away like dust.": "风雷听我号令！你们这点人马，一阵风便扫个干净！",
    # ---- side: the Way of Great Peace ----
    "The Way of Great Peace · I: The Old Man in the Cave": "太平道·一：洞中老人",
    "Years before, the man who would lead the Yellow Turbans was only a failed scholar named Zhang Jiao. One day he went into the hills to gather herbs.": "多年以前，那位日后统领黄巾的人，还只是个不第秀才，名叫张角。一日，他入山采药。",
    "There he met an old man with green eyes and a child's face, leaning on a staff, who led him into a cave.": "他遇见一位老人，碧眼童颜，手执藜杖，唤他进了一个山洞。",
    "These three books are the Essentials of Great Peace. Take them, spread Heaven's teaching, and save the world. But harbour one rebellious thought, and you will be punished.":
        "此三卷天书，名为《太平要术》。你得了它，当代天宣化，普救世人。若萌异心，必获恶报。",
    "Master, what is your name?": "敢问老仙尊姓大名？",
    "I am the Old Immortal of Southern Florescence.": "吾乃南华老仙也。",
    "And he vanished in a breath of wind.": "说完，化作一阵清风而去。",
    "The Way of Great Peace · II: The Blue Heaven Is Dead": "太平道·二：苍天已死",
    "Zhang Jiao studied the books day and night until he could summon wind and rain. When plague swept the land, he went about giving out charmed water, and the sick recovered.": "张角日夜苦学，能呼风唤雨。瘟疫流行之时，他散施符水，为人治病。",
    "They called him the Great and Virtuous Teacher. His disciples numbered in the hundreds of thousands, organised in thirty-six divisions.": "人们称他为大贤良师。他的徒众日多，立三十六方。",
    "The Blue Heaven is dead! The Yellow Heaven shall rise! In the year jiazi, great fortune for all under Heaven!": "苍天已死，黄天当立；岁在甲子，天下大吉！",
    "Across eight provinces, families chalked the word jiazi on their doors.": "八州百姓，家家在大门上用白土写上“甲子”二字。",
    "The Way of Great Peace · III: Betrayed": "太平道·三：事泄",
    "The hardest thing in the world to win is the people's hearts — and now they are ours. To let this moment pass would be a crime.": "至难得者，民心也。今民心已顺，若不乘势取天下，诚为可惜。",
    "He bribed a eunuch in the palace to open the gates from within. But his disciple Tang Zhou carried the plan straight to the court. In Luoyang, his agent Ma Yuanyi was beheaded.":
        "他暗中结交宫中宦官作为内应。不料弟子唐周赴朝廷告变，党羽马元义在洛阳被斩。",
    "Then we rise now. I am the General of Heaven. Zhang Bao, you are General of Earth. Zhang Liang, General of Man.": "那就即刻起兵！我为天公将军，张宝为地公将军，张梁为人公将军！",
    "Half a million rose in yellow scarves, and the imperial armies scattered before them like leaves.": "四五十万百姓裹黄巾相从，官军望风而靡。",
    # ---- side: Cao Cao ----
    "The Hero of Chaos · I: The Feigned Stroke": "奸雄·一：诈中风",
    "Far to the south, in Qiao, a boy named Cao Cao loved hunting, music and mischief — and his uncle kept telling his father so.": "沛国谯郡有个少年，名叫曹操，好游猎，喜歌舞。他的叔父屡次向他父亲告状。",
    "So one day, seeing his uncle coming, Cao Cao dropped to the ground, twitching.": "有一天，曹操见叔父走来，便诈倒在地，装作中风的样子。",
    "Brother! Your son has had a stroke!": "兄长！你儿子中风了！",
    "A stroke? I've never had one in my life. Uncle just dislikes me, so he tells tales about me.": "儿子自来没有这病。只因叔父不喜欢我，所以冤枉我罢了。",
    "From then on, whatever the uncle reported, Cao Cao's father never believed a word.": "从此以后，叔父再说曹操的不是，父亲一概不听。",
    "The Hero of Chaos · II: A Villain in Chaos": "奸雄·二：乱世奸雄",
    "When he was grown, Cao Cao went to see Xu Shao of Runan, who was famous for judging men.": "曹操长大后，前去拜见以善于识人闻名的汝南许劭。",
    "What kind of man am I?": "我是怎样的人？",
    "Xu Shao would not answer. Cao Cao asked again.": "许劭不答。曹操又问。",
    "In an age of order, an able minister. In an age of chaos — a cunning villain.": "子治世之能臣，乱世之奸雄也。",
    "Cao Cao laughed with delight. Later, as a captain in Luoyang, he hung coloured staves at the city gates and flogged anyone caught breaking curfew — even the uncle of the eunuch Jian Shuo. After that, nobody dared.":
        "曹操听了大喜。后来他任洛阳北都尉，在城门设五色棒，犯禁者不避豪强，连宦官蹇硕的叔父也照打不误。从此再无人敢犯。",
    "The Hero of Chaos · III: Red Banners at Changshe": "奸雄·三：长社红旗",
    "At Changshe, the Yellow Turbans pitched their camp in tall grass.": "长社一带，黄巾依草结营。",
    "They camp in grass. Fire will take them. Every man, bring a bundle of straw.": "贼依草结营，当用火攻。每人束草一把，暗地埋伏！",
    "That night a great wind rose. The camp went up in flames; the rebels fled without saddles or armour.": "当夜大风忽起，一齐纵火，火焰张天。贼众马不及鞍，人不及甲，四散奔逃。",
    "At dawn, as Zhang Bao and Zhang Liang ran, a column under red banners barred the road.": "天明时分，张梁、张宝夺路而走，忽见一彪军马，尽打红旗，截住去路。",
    "Cao Cao, Commandant of Cavalry. You go no further.": "骑都尉曹操在此，休想过去！",
    "Ten thousand heads were taken. The two brothers barely escaped with their lives.": "曹操斩首万余级，张梁、张宝死战得脱。",
    # ---- side: shortcuts ----
    "Horses from the North": "北来骏马",
    "The brothers had men, but no horses. Then two travelling merchants, Zhang Shiping and Su Shuang, came down the trail driving a herd.": "兄弟三人有了人马，却苦无马匹。正在发愁，中山大商张世平、苏双赶着一群马来到庄上。",
    "Bandits have closed the road north. If you mean to crush them, take fifty horses — and five hundred taels of silver, and a thousand jin of steel for your weapons.":
        "贼寇阻断了北去的路。诸位既要讨贼，我们愿送良马五十匹，金银五百两，镔铁一千斤，以资器用。",
    "Liu Bei has twin swords forged. Guan Yu's blade is the Green Dragon Crescent, eighty-two jin, called Cold Beauty. Zhang Fei's is an eighteen-foot serpent spear of steel.":
        "刘备打造双股剑；关羽造青龙偃月刀，又名冷艳锯，重八十二斤；张飞造丈八点钢矛。",
    "A Bribe Refused": "拒贿",
    "At Guangzong, Lu Zhi had Zhang Jiao penned in, though the rebel's sorcery kept him from the final blow. Then the court's envoy arrived: the eunuch Zuo Feng.": "卢植在广宗围住张角，只因张角会妖术，一时未能取胜。这时，朝廷派来的使者到了，是宦官左丰。",
    "Your victories are splendid, general. And where is the gift for the Emperor's envoy?": "将军连战连捷，可喜可贺。那么，孝敬天使的礼物在哪里？",
    "My army lacks grain. Where would I find money to flatter an envoy?": "军粮尚缺，安有余钱奉承天使？",
    "Zuo Feng rode back to Luoyang and reported that Lu Zhi skulked behind his walls and would not fight.": "左丰怀恨，回京奏报：卢植高垒不战，惰慢军心。",
    # ---- closing ----
    "The Yellow Turbans Fall": "黄巾覆灭",
    "But the eunuchs gave rewards only to those who paid. For all his battles, Liu Bei was made a mere county sheriff, at Anxi.": "可是宦官只赏送礼之人。刘备大小三十余战，只得了个安喜县尉。",
    "You claim imperial blood and invent your merits! The court is purging frauds like you.": "你诈称皇亲，虚报功绩！朝廷正要沙汰你这等滥官！",
    "Tormentor of the people! Do you know who I am?": "害民贼！认得我么？",
    "Lord Xuande! Save my life!": "玄德公，救我性命！",
    "Chapter 2": "第二回",
    "Emperor Ling died. In the capital, his brother-in-law, General He Jin, resolved to destroy the eunuchs at last — and sent for the warlords of the provinces to march on Luoyang and force the Empress's hand.":
        "灵帝驾崩。大将军何进决意诛杀宦官，发檄文召四方诸侯领兵进京。",
    "“A mistake,” warned his secretary Chen Lin. “You hand the spear to others, point first.”": "主簿陈琳劝道：“不可！这是倒持干戈，授人以柄。”",
    "A man beside them clapped and laughed. “This is as easy as turning over a hand. Why so much talk?” It was Cao Cao.": "旁边一人鼓掌大笑：“此事易如反掌，何必多议！”此人正是曹操。",
    "What did Cao Cao propose? Hear the next chapter.": "不知曹操说出甚话来，且听下文分解。",
    "The Inspector's Visit": "督邮驾到", "The Hitching Post": "县前马桩",
    "Fortune favours the one who reads the stones.": "能看懂这盘棋的人，自有天佑。",
    "Liu Bei goes into the tent and bows to his old teacher. Lu Zhi is glad to see him, and keeps him at his side.": "入帐施礼，具道来意。卢植大喜，留在帐前听调。",
    "I hear my old teacher Lu Zhi is fighting Zhang Jiao at Guangzong. I once studied under him, and I wish to go and help.": "近闻中郎将卢植与贼首张角战于广宗，备昔曾师事卢植，欲往助之。",
    "Meet the inspector at the posting station.": "到驿馆拜见督邮。",
    "Go to the county office, where the old villagers are gathering.": "到县衙前，老人们正聚在那里。",
    # ---- World 1: staging pass, lines that changed or are new ----
    "Cao Cao laughed with delight.": "操闻言大喜。",
    "The Hero of Chaos · II-b: The Five-Coloured Staves": "乱世英雄·二之二：五色棒",
    "Cao Cao is made captain of the north district of Luoyang. As soon as he takes office, he hangs more than ten coloured staves at the four gates of the city.": "操举孝廉，为郎，除洛阳北部尉。初到任，即设五色棒十余条于县之四门。",
    "Anyone who breaks the curfew is beaten, rich or powerful alike.": "有犯禁者，不避豪贵，皆责之。",
    "One night the uncle of the eunuch Jian Shuo walks the street with a sword in his hand. Cao Cao's patrol catches him.": "中常侍蹇硕之叔，提刀夜行，操巡夜拿住。",
    "Cao Cao has him beaten with the staves.": "操就棒责之。",
    "After that, no one inside the city or out dares to break the rule, and Cao Cao's name spreads.": "由是内外莫敢犯者，威名颇震。",
    "He bribed a eunuch in the palace to open the gates from within. But his disciple Tang Zhou carried the plan straight to the court.": "遣其党马元义，暗赍金帛，结交中涓封谞，以为内应。弟子唐州乃径赴省中告变。",
    "His agent Ma Yuanyi, who had carried the bribe to Luoyang, was caught and beheaded.": "送贿入洛阳的马元义被擒，斩于市。",
    # ---- World 1: the horse dealers are a main story point (ch. 1) ----
    "The next day they gather their weapons, but they have no horses to ride.": "来日收拾军器，但恨无马匹可乘。",
    "While they are still worrying, word comes of two horse dealers, Zhang Shiping and Su Shuang, camped on the northern trail with a herd of horses.": "正思虑间，人报北边路上来了两个马商，一名张世平，一名苏双，赶着一群马，在路边歇下。",
    "This is Heaven's help!": "此天佑我也！",
    # ---- World 1: the third brother joins at the inn (ch. 1) ----
    "The Stranger at the Inn": "村店遇云长",
    "Liu Bei is delighted, and the two go into the village inn to drink.": "玄德甚喜，遂与同入村店中饮酒。",
    # ---- World 1: indoor scenes (ch. 1) ----
    "The Governor's Council": "太守议事",
    "Lu Zhi's Tent": "卢植帐中",
    "The Fire Plan": "火攻之计",
    "The Yellow Turbans have crossed into You Province. Governor Liu Yan summons his officer Zou Jing.": "黄巾前犯幽州界分。太守刘焉闻得贼兵将至，召校尉邹靖计议。",
    "Zou Jing advises him: “The rebels are many and our soldiers are few. My lord, you should raise troops at once, and meet them.”": "邹靖曰：“贼兵众，我兵寡，明公宜作速招军应敌。”",
    "Liu Yan agrees, and has a notice posted calling for volunteers. It goes up on the wall at Zhuo County, and it draws out a hero.": "刘焉然其说，随即出榜招募义兵。榜文行到涿县，乃引出涿县中一个英雄。",
    "With Qingzhou relieved, Liu Bei hears that his old teacher Lu Zhi is fighting Zhang Jiao at Guangzong, and goes to help him. Lu Zhi is glad to see him, and keeps him in the tent.": "青州之围已解。玄德闻中郎将卢植与贼首张角战于广宗，备昔曾师事卢植，欲往助之。至卢植军中，入帐施礼，具道来意。卢植大喜，留在帐前听调。",
    "I have Zhang Jiao penned in here. His brothers Zhang Liang and Zhang Bao are at Yingchuan, facing the court's generals, Huangfu Song and Zhu Jun.": "我今围贼在此。贼弟张梁、张宝在颍川，与朝廷大将皇甫嵩、朱儁对垒。",
    "Take your own men, and I will give you a thousand more. Go to Yingchuan, learn how they stand, and we will fix a day to destroy them.": "汝可引本部人马，我更助汝一千官军，前去颍川打探消息，约期剿捕。",
    "Liu Bei takes his orders, and marches through the night.": "玄德领命，引军星夜投颍川来。",
    "Every man is told to carry a bundle of straw, and hide it.": "遂令军士，每人束草一把，暗地埋伏。",
    # ---- World 1: the mulberry tree (ch. 1) ----
    "The Mulberry Tree at Lousang": "楼桑村的大桑树",
    "South-east of his house stands a mulberry tree more than fifty feet tall. From far off, it looks like the canopy over an emperor's carriage.": "他家东南有一棵大桑树，高五丈余，遥望之，童童如车盖。",
    "A passing fortune-teller looks at it and says: this house will produce a great man.": "相者见了，说：“此家必出贵人。”",
    "Liu Bei's father died early. As a boy he plays under the tree with the village children.": "玄德幼孤，与乡中小儿戏于树下。",
    "When I am the Son of Heaven, I will ride under a canopy like this!": "我为天子，当乘此车盖！",
    "This is no ordinary child!": "此儿非常人也！",
    "The family is poor. His uncle Liu Yuanqi helps them from then on.": "叔父刘元起见玄德家贫，常资给之。",
    "At fifteen, his mother sends him to study under Zheng Xuan and Lu Zhi, and he befriends Gongsun Zan.": "年十五岁，母使游学，尝师事郑玄、卢植，与公孙瓒等为友。",
    "He serves his mother with the utmost devotion.": "玄德事母至孝。",
    "Years pass. By the time the governor calls for volunteers, Liu Bei is twenty-eight.": "及刘焉发榜招军时，玄德年已二十八岁矣。",
    # ---- World 1: transitions (ch. 1-2) ----
    "Liu Bei and his five hundred report to the governor, Liu Yan. Learning that Liu Bei is of the same imperial house, Liu Yan is delighted and takes him as a nephew.": "刘备引兵五百来见太守刘焉。玄德说起宗派，刘焉大喜，遂认玄德为侄。",
    "Not many days later, the Yellow Turban general Cheng Yuanzhi marches on Zhuo with fifty thousand men. Liu Bei meets him with five hundred.": "不数日，黄巾贼将程远志统兵五万来犯涿郡。刘焉令邹靖引玄德等三人，统兵五百，前去破敌。",
    "A letter comes from Gong Jing, governor of Qingzhou: the Yellow Turbans have his city surrounded, and it is about to fall. He begs for help.": "接得青州太守龚景牒文，言黄巾贼围城将陷，乞赐救援。",
    "A messenger runs in with a letter from Gong Jing, governor of Qingzhou: the Yellow Turbans have his city surrounded, and it is about to fall. He begs for help.": "接得青州太守龚景牒文，言黄巾贼围城将陷，乞赐救援。",
    "I will go and rescue it.": "备愿往救之。",
    "Qingzhou is relieved. Liu Bei hears that his old teacher Lu Zhi is fighting Zhang Jiao himself at Guangzong, and goes to help him.": "青州之围已解。玄德闻中郎将卢植与贼首张角战于广宗，备昔曾师事卢植，欲往助之。",
    "Lu Zhi is glad to see him, and keeps him at his tent. Then he sends him with a thousand more men to Yingchuan, to learn how Huangfu Song and Zhu Jun are doing against Zhang Jiao's brothers.": "卢植大喜，留在帐前听调，又添一千官军，令玄德往颍川打探皇甫嵩、朱儁与张角二弟交战的消息。",
    "By the time Liu Bei arrives, the rebels have been routed by fire. Huangfu Song tells him the brothers will run to Zhang Jiao at Guangzong, and he turns back through the night.": "玄德赶到颍川，贼已败散。皇甫嵩曰：“张梁、张宝势穷力乏，必投广宗去依张角。玄德可即星夜往助。”玄德领命，遂引兵复回。",
    "Halfway back to Guangzong, they meet soldiers guarding a prison cart.": "回广宗的路上，行到半路，只见一簇军马，护送一辆槛车。",
    "The cart rolls away toward Luoyang.": "槛车往洛阳去了。",
    "Lu Zhi is under arrest, and Dong Zhuo has his army. We have no one left to turn to here. Let us go back to Zhuo.": "卢中郎已被逮，兵马归了董卓，我等去无所依，不如且回涿郡。",
    "Liu Bei agrees, and they march north. Again the road divides.": "玄德从其言，遂引军北行。前路又一次分岔。",
    "Zhu Jun receives them warmly. The two armies join, and Zhu Jun makes Liu Bei his vanguard against Zhang Bao.": "朱儁待之甚厚，合兵一处，进讨张宝，令玄德为其先锋，与贼对敌。",
    "Liu Bei tells him his own aim, and Guan Yu is delighted. The three go together to Zhang Fei's farm to plan their great enterprise.": "玄德遂以己志告之，云长大喜。三人同到张飞庄上，共议大事。",
    "Very good.": "如此甚好。",
    "The next day, in the peach garden behind Zhang Fei's farm, the blossoms are in full bloom.": "次日，张飞庄后的桃园中，花开正盛。",
    # ---- World 1 plot pass (from docs/world1-script-draft.md) ----
    "Zhuo County. A crowd gathers at a notice on the wall: the governor is raising volunteers to put down the Yellow Turbans.": "涿县城中，众人围看墙上榜文：幽州太守刘焉出榜招募义兵，讨平黄巾。",
    "Under an old pine by the road sit the two white-haired men from the peach garden, over a board on a flat rock, as if no army were coming.": "路旁老松树下，桃园中那两位白发老人又对着盘石上的棋局坐着，仿佛大军压境与他们无关。",
    "Read this first.": "先看这一局。",
    "To catch the bandits, first catch their king.": "擒贼先擒王。",
    "That night, at the edge of the camp, the two old men are at their board again.": "当夜营边，两位老人又在对弈。",
    "Another.": "再看这一局。",
    "Don't hold the strong point. Give ground, and make them follow.": "莫守坚城。且退一步，引他来追。",
    "If I don't kill him, I'll have to take his orders, and I won't. Stay here if you like, brothers. I'm going elsewhere.": "若不杀这厮，反要在他部下听令，其实不甘！二兄要便住在此，我自投别处去也！",
    "We three are bound in life and death. How could we part? Then we will all go elsewhere.": "我三人义同生死，岂可相离？不若都投别处去便了。",
    "If so, that eases my anger a little.": "若如此，稍解吾恨。",
    "At a roadside shrine the two old men sit over their board, as if nothing were happening.": "路旁小庙前，两位老人依旧对坐弈棋，若无其事。",
    "Read this, before you run.": "先看此局，再跑不迟。",
    "Pigs, sheep, dogs. Blood.": "猪、羊、狗。血。",
    "Guan Yu and Zhang Fei each take a thousand men up the ridge behind the hill, with the blood and filth.": "关、张二人各引军一千，伏于山后高冈之上，备下猪羊狗血并秽物。",
    "Zhu Jun's army surrounds Yangcheng. Zhang Bao holds the walls and will not come out. Behind him stands his own officer, Yan Zheng.": "朱儁引兵围住阳城。张宝紧守城池，不敢出战。他身后，立着部将严政。",
    "Yan Zheng stabs him, and carries his head out to surrender.": "严政刺杀张宝，献首投降。",
    "At Guangzong, Huangfu Song took over from Dong Zhuo, but Zhang Jiao had already died of illness. Huangfu Song beat Zhang Liang in seven battles and broke open the Great Teacher's coffin. The rebellion was over.": "广宗一路，皇甫嵩接替董卓，到时张角已经病死。皇甫嵩与张梁交战，连胜七阵，斩张梁，发张角之棺，戮尸枭首。黄巾之乱就此平定。",
    "At Wancheng, Liu Bei gave Zhu Jun some advice: “Surround them completely and every man fights to the death. Leave them one way out, and they will run.” It worked. There too, a young officer named Sun Jian was first over the wall: a name to remember.": "在宛城，刘备向朱儁进言：“今四面围如铁桶，贼必死战；不若撤去东南，独攻西北，贼必弃城而走。”果然奏效。也是在宛城，一位名叫孙坚的年轻将领首先登城，这个名字，日后还要记住。",
    "At Anxi, Liu Bei governs for a month and wrongs no one. The three eat at one table and sleep in one bed. When Liu Bei sits among crowds, Guan Yu and Zhang Fei stand at his side all day without tiring.": "玄德到安喜县，署县事一月，与民秋毫无犯。与关、张食则同桌，寝则同床。如玄德在稠人广坐，关、张侍立，终日不倦。",
    "Less than four months after he took office, an edict orders officers with military merit to be culled. Liu Bei fears he is among them. An inspector arrives.": "到县未及四月，朝廷降诏，凡有军功为长吏者当沙汰。玄德疑在遣中。适督邮行部至县。",
    "Liu Bei goes out of the city to greet him. The inspector stays on his horse and answers with a small flick of his whip. Guan Yu and Zhang Fei are furious.": "玄德出郭迎接，见督邮施礼。督邮坐于马上，惟微以鞭指回答。关、张二公俱怒。",
    "At the hostel the inspector sits facing south; Liu Bei stands below the steps.": "及到馆驿，督邮南面高坐，玄德侍立阶下。",
    "What is your origin, Sheriff Liu?": "刘县尉是何出身？",
    "I descend from Prince Jing of Zhongshan. I fought the Yellow Turbans from Zhuo County in over thirty battles.": "备乃中山靖王之后；自涿郡剿戮黄巾，大小三十余战，颇有微功，因得除今职。",
    "Liu Bei asks his clerks what to do. The inspector only wants a bribe, they say. But Liu Bei has taken nothing from the people, and has nothing to give. The inspector seizes the clerks, and each time Liu Bei comes to plead, he is turned away at the gate.": "玄德与县吏商议。吏曰：督邮作威，无非要贿赂耳。玄德与民秋毫无犯，那得财物与他？督邮便提县吏去；玄德几番自往求免，俱被门役阻住。",
    "Zhang Fei, a few cups of gloomy wine in, rides past the hostel and finds fifty or sixty old villagers weeping at the gate.": "张飞饮了数杯闷酒，乘马从馆驿前过，见五六十个老人，皆在门前痛哭。",
    "The inspector is forcing the clerks to accuse Liu Bei, they tell him, and the gatekeepers beat them away when they come to plead for him.": "老人说：督邮逼勒县吏，欲害刘公；我等皆来苦告，不得放入，反遭把门人赶打！",
    "He drags the inspector out by the hair, to the hitching post before the county office, and ties him there.": "张飞揪住督邮头发，扯出馆驿，直到县前马桩上缚住。",
    "Zhang Fei breaks ten or more willow switches across his legs.": "攀下柳条，去督邮两腿上着力鞭打，一连打折柳条十数枝。",
    "Liu Bei, a gentle man at heart, orders Zhang Fei to stop.": "玄德终是仁慈的人，急喝张飞住手。",
    "Brother, you won great merit and were given only a sheriff's post, and now an inspector insults you. A phoenix does not roost among thorns. Let us kill him, give up the office, and make greater plans elsewhere.": "兄长建许多大功，仅得县尉，今反被督邮侮辱。吾思枳棘丛中，非栖鸾凤之所；不如杀督邮，弃官归乡，别图远大之计。",
    "For what you have done to the people you deserve to die. I spare your life. I return my seal of office, and I am gone.": "据汝害民，本当杀却；今姑饶汝命。吾缴还印绶，从此去矣。",
    "He hangs the seal around the inspector's neck.": "玄德取印绶，挂于督邮之颈。",
    # ---- ladies and girls about town ----
    "“Brother Xuande! When you're rich, will you buy me a hairpin with a flower on it?”": "“玄德哥哥！等你富贵了，给我买一支带花的簪子好不好？”",
    "“They say the volunteers march next month. Half the girls in town will be weeping at the gate.”": "“听说义兵下月就要出征，城里一半的姑娘都要在城门口哭了。”",
    "“A man nine feet tall, with a face as red as a ripe date, just walked into the inn. Who do you suppose he is?”": "“刚才有个身长九尺、面如重枣的大汉进了酒店，你说他是什么人？”",
    "“More tea? The storyteller's tale of the Yellow Turbans is the talk of the county.”": "“再添些茶吧？说书先生讲的黄巾故事，全县都在传呢。”",
    # ---- World 1 places: townsfolk, challengers and story spots (tools/tk_places.py) ----
    "“Off to sell your sandals in town, Xuande? Mind the road.”": "“玄德，又进城卖草鞋？路上小心。”",
    "“That mulberry looks like a carriage canopy! Mother says someone from this house will ride under one.”": "“那棵桑树长得像车盖！娘说，这家将来要出贵人。”",
    "“The Yellow Turbans are burning villages in the south. Strange times.”": "“黄巾贼在南边烧村子，真是乱世啊。”",
    "Your neighbour has scratched a weiqi board into the dirt under the mulberry. “Before you go to town, Xuande, one game.”": "邻居在桑树下的泥地上画了一张棋盘。“玄德，进城之前，先下一局。”",
    "“Ha! Sharper than your sandals. Go on, then.”": "“哈！你的棋比你的草鞋还精。去吧。”",
    "“Bring me back a story from town.”": "“从城里带个新鲜事回来给我听。”",
    "Liu Bei answers by reading the rest of the notice. Below the governor's call for volunteers is a weiqi problem: “Let any man who would lead volunteers show he can read a battle.”": "玄德答话之前，先看完榜文。太守招募义兵的告示下面，附着一道围棋题：“欲率义兵者，先请看清此局。”",
    "An old storyteller taps his clapper-board. “Sit, sit! Tales of the Yellow Heaven…”": "一位说书老人敲了敲醒木。“坐，坐！且听黄天的故事……”",
    "“They say the Yellow Turbans wear scarves the colour of the earth.”": "“听说黄巾贼头上裹的巾，是土黄色的。”",
    "“Liu Bei? The sandal-seller? Kind man. Ears down to his shoulders, you know.”": "“刘备？那个卖草鞋的？是个好人。耳朵都垂到肩膀了。”",
    "“Zhang Fei sells wine and pork. Loud as thunder, but his heart is good.”": "“张飞卖酒杀猪，嗓门像打雷，心肠却好。”",
    "“The governor wants volunteers. Read the notice.”": "“太守在招义兵，你去看看榜文吧。”",
    "An old man sits over a weiqi board in the square. “You have the look of a thinker. Sit, play me one.”": "广场上，一位老人守着一张棋盘。“看你像个有心思的人。坐，陪我下一局。”",
    "“Ha! Quick eyes. The governor could use a man like you.”": "“哈！好眼力。太守正需要你这样的人。”",
    "“Go on. I'll sit here a while yet, still thinking about that board.”": "“去吧。我还要在这儿坐一会儿，琢磨琢磨那盘棋。”",
    "“Wine's on the house if you can solve the one my regulars can't.”": "“我这儿的老主顾都解不出这道题。你要是解得出，酒钱全免。”",
    "“Well I never. Drink up, then!”": "“真没想到！那就喝吧！”",
    "“Still the only one who's cracked it.”": "“到现在还只有你一个人解出来。”",
    "“Weiqi's like farming: you claim the land, then you have to hold it. Try this.”": "“下棋跟种地一样：先占地，还得守得住。试试这道。”",
    "“Held it, and well.”": "“守住了，守得好。”",
    "“Fine soil this year.”": "“今年的地真肥。”",
    "A clerk from the county office looks up. “The magistrate set this one. Nobody here has solved it.”": "县衙的一位书吏抬起头。“这道题是县令出的，这里还没人解得出。”",
    "“Remarkable. I'll tell the magistrate a sandal-seller did it.”": "“了不起。我要告诉县令，是个卖草鞋的解出来的。”",
    "“The magistrate still doesn't believe me.”": "“县令到现在还不信我。”",
    "Under the great peach tree two old men sit over a weiqi board, one in grey, one in red.": "大桃树下，两位老人对坐下棋，一位穿灰衣，一位穿红衣。",
    "Three young men, come to swear before Heaven? Heaven is listening. But first, show us how you read the stones.": "三位年轻人，要来对天盟誓吗？上天在听着。不过，先让我们看看你们怎么看这盘棋。",
    "Good. The road ahead forks, and fortune favours the one who reads it.": "好。前路分岔，福气只眷顾看得清路的人。",
    "When the brothers look up, the two old men are gone. Only the board remains, and a drift of petals.": "兄弟三人抬起头时，两位老人已不见踪影，只剩下一盘棋和满地落花。",
    "The old man in grey studies the board and says nothing.": "灰衣老人凝视着棋盘，一言不发。",
    "“Patience. Heaven is in no hurry.”": "别急。上天从不着急。",
    "“An old man lives up in the hills. Gathers herbs. Some say he's an immortal.”": "“山里住着一位采药的老人，有人说他是神仙。”",
    "“The black wind took my roof. Take the pigs' blood, if it ends this.”": "“黑风掀了我的屋顶。若能破了妖风，猪血你们尽管拿去。”",
    "“My flock hasn't grazed since the storm. Take a sheep, general. Take what you need.”": "“羊群自风起后便没吃过草。将军要多少，只管取去。”",
    "“My hounds won't go near that hill. If their blood breaks the spell, take it.”": "“我的猎犬不肯近那座山。若用狗血能破法，你们拿去。”",
    "“The Way of Great Peace heals the sick. Drink the charm-water, brother.”": "“太平道能治百病。兄弟，喝一碗符水吧。”",
    "“Half the county wears yellow now.”": "“现在半个县的人都裹上黄巾了。”",
    "“Fine northern horses, but the roads are full of bandits.”": "“北方的好马是有，可路上全是强盗。”",
    "“The rebels have us surrounded. If only someone could draw them off…”": "“贼兵把我们围住了。要是有人能把他们引开就好了……”",
    "“The new commandant of the north gate beats curfew-breakers to death. Even the eunuchs' uncles.”": "“北门新来的都尉，犯夜禁的一律打死，连宦官的叔父也不放过。”",
    "“The general is in his tent. He doesn't like visitors without rank.”": "“将军在帐里。他不喜欢没官职的人来见他。”",
    "“Wind and thunder answer to me!”": "风雷听我号令！",

    # ---- World 1 places, objectives and story spots (map factory, tk-world.js) ----
    "Lousang Village": "楼桑村", "Zhuo County": "涿县", "The Peach Garden": "桃园", "Road to Julu": "巨鹿道上",
    "Julu": "巨鹿", "Yellow Hills": "黄冈", "Horse Trail": "马道", "Daxing Mountain": "大兴山", "Qingzhou": "青州",
    "Guangzong Road": "广宗道上", "Qiao": "谯郡", "Luoyang Gates": "洛阳城门", "Changshe": "长社",
    "Envoy's Road": "使者路上", "The Hills North of Guangzong": "广宗以北的山岭", "Hills of Black Wind": "黑风岭", "Yangcheng": "阳城",
    "Sit under the great mulberry tree by your home.": "到屋旁的大桑树下坐坐。",
    "Go into the county town. The governor is calling for men.": "进县城去。太守正在招募人马。",
    "Go into the village inn.": "走进村店。",
    "Report to Lu Zhi in his tent.": "到卢植帐中拜见。",
    "Read the notice in the town square.": "去城中广场看榜文。",
    "Sit at the old men's weiqi board under the great peach tree.": "在大桃树下，坐到两位老人的棋盘前。",
    "Side story: find the old man in the hills.": "支线：去山中寻找那位老人。",
    "Side story: hear Zhang Jiao's sermon in Julu.": "支线：到巨鹿听张角传道。",
    "Side story: the betrayal in the Yellow Hills.": "支线：黄冈的背叛。",
    "Meet the horse dealers on the northern trail.": "到北方马道上见马商。",
    "Go to Daxing Mountain. The Yellow Turbans are marching on Zhuo.": "到大兴山去。黄巾军正向涿郡进发。",
    "Lift the siege of Qingzhou.": "解青州之围。",
    "Go to Guangzong, where Lu Zhi besieges Zhang Jiao.": "前往广宗，卢植正在那里围攻张角。",
    "Side story: the boyhood of Cao Cao.": "支线：曹操的少年时代。",
    "Side story: Cao Cao at the gates of Luoyang.": "支线：洛阳城门的曹操。",
    "Side story: red banners at Changshe.": "支线：长社红旗。",
    "Side story: the five-coloured staves at the city gates.": "支线：城门上的五色棒。",
    "Side story: the fire plan in the Han camp.": "支线：汉军营中的火攻之计。",
    "Shortcut: the envoy on the road.": "捷径：路上的使者。",
    "Head home to Zhuo.": "回涿郡去。",
    "Break Zhang Bao's sorcery in the hills.": "在山中破张宝的妖术。",
    "Yingchuan, Too Late": "颍川，来迟一步",
    "Hear the messenger from Qingzhou.": "听青州来的信使怎么说。",
    "The very next day, a messenger gallops in from Qingzhou.": "次日，青州有快马飞报而来。",
    "Some days before Liu Bei reaches Yingchuan, in the Han camp at Changshe…": "在玄德赶到颍川的几天前，长社的汉军大营里……",
    "Days before Liu Bei reached Yingchuan, the rebels fled the flames at Changshe.": "玄德赶到颍川的几天前，贼兵在长社逃出火海。",
    "Not Yet": "尚早",
    "The left hill": "左侧山岭",
    "The right hill": "右侧山岭",
    "The field before the city": "城前旷野",
    "Where the army was": "官军曾驻之处",
    "Brother! Is that the blood? Up here, quickly!": "兄长！那是血吗？快送上来！",
    "Brother! Is that the blood? Bring it up here!": "兄长！可是血来了？快拿上来！",
    "Brother, send me! The left hill is mine.": "兄长，派我去！左边那座山岭归我。",
    "Brother, send me! Put me on the right hill.": "兄长，派我去！让我守右边山岭。",
    "The ridge is empty. Read the roadside shrine first.": "山岭上空无一人。先去路边神龛。",
    "No one is on this hill yet. Hear the messenger first.": "这座山岭上还没有人。先听信使怎么说。",
    "Not yet. Yunchang must be on the left hill and Yide on the right, before I strike.": "还不是时候。须待云长伏于左岭、翼德伏于右岭，我方可出击。",
    "The old men said blood. Pigs, sheep, dogs. We have none. Go to the farm east of the pine and ask.": "老人说要血：猪、羊、狗。我们一样也没有。去大松树东边的农庄讨来。",
    "Give ground, and make them follow.": "退一步，引他来追。",
    "“General! The pigs' blood is ready for you!”": "“将军！猪血给您备好了！”",
    "“General, over here! Take a sheep, if it helps.”": "“将军，这边！要羊血尽管拿去。”",
    "“General! My hounds are yours, if it ends this.”": "“将军！只要能了结此事，我的猎犬任您取用。”",
    "A man behind him, with a leopard's head, round eyes and a voice like thunder, cries out. This is Zhang Fei, who farms near Zhuo, sells wine and slaughters pigs.": "忽然背后一人厉声大叫：豹头环眼，声若巨雷。此人姓张名飞，字翼德，世居涿郡，卖酒屠猪。",
    "No one is on this hill yet.": "这座山岭上还没有人。",
    "A thousand men, hidden on the left. I wait for the gongs.": "一千人马伏于山左，只等鸣金。",
    "The right hill is mine. I will hear the gongs from a mile off.": "右边山岭归我。十里之外我也听得见锣响。",
    "Go to Changshe, in Yingchuan, and learn how Huangfu Song and Zhu Jun stand.": "去颍川长社，探明皇甫嵩、朱儁的军情。",
    "Liu Bei sends the army out, but the hills on either side are empty, and the rebels press him back.": "玄德引军出战，两侧山岭上却空无一人，被贼兵逼退。",
    "Not yet. Yunchang and Yide must be on their hills first.": "还不是时候。须先让云长、翼德各上山岭。",
    "Liu Bei marches through the night to Yingchuan. When he arrives, the rebels have been routed by fire.": "玄德星夜赶到颍川，见贼已被火攻击溃。",
    "Zhang Liang and Zhang Bao have no strength left. They will run to Guangzong, to Zhang Jiao. Go back at once, and help.": "张梁、张宝势穷力乏，必投广宗去依张角。玄德可即星夜往助。",
    "Liu Bei takes his orders, and turns his army back through the night.": "玄德领命，遂引兵复回。",
    "Sorcery. A man cannot fight a wind. Fall back to the road.": "此乃妖术，人如何与风相战？退回大路。",
    "On a flat rock under the pine, where the stones glow, sit the two white-haired men from the peach garden, as if nothing had happened.": "大松树下的盘石上，棋子微微发光。桃园中那两位白发老人对坐其旁，仿佛什么也没发生。",
    "Read this, before you go back.": "回去之前，先看看这一局。",
    "Zhu Jun's own men have no blood to spare. In the village below the hills there are pens, flocks and hounds. Liu Bei goes down to ask.": "朱儁军中无血可用。山下村中有猪圈、羊群和猎犬，玄德下山去问。",
    "Zhu Jun's own men have no blood to spare. But at the farm just east of the pine, the farmers keep pigs, sheep and hounds.": "朱儁军中无血可用。大松树东边不远有座农庄，庄户人家养着猪、羊和猎犬。",
    "The Shrine at the Roadside": "路旁神龛",
    "Liu Bei marches on Yangcheng with nothing to break the sorcery. Again Zhang Bao lets down his hair and chants.": "玄德引军至阳城，无破妖术之物。张宝又披发仗剑作法。",
    "Again the black wind pours out of the cloud. The army breaks.": "黑气再起，风雷大作，军马溃走。",
    "No man can fight a wind. Fall back.": "人如何与风相战？退！",
    "The Wind Again": "风势再起",
    "The old men said blood. Pigs, sheep, dogs. We have none.": "老人说过：血，猪、羊、狗血。我们一样也没有。",
    "Defeat the Black Wind.": "破黑风妖法。",
    "“The black wind has been bad this month.”": "“这个月黑风厉害。”",
    "“Keep off the hills, general.”": "“将军，别上那座山。”",
    "“My hounds won't go near that hill.”": "“我的猎犬不肯近那座山。”",
    "“You have my pigs' blood. Go, and stop this wind.”": "“猪血你们已经拿走了。去吧，把这风止住。”",
    "“You've had the best of my flock, general. Go on.”": "“我羊群里最好的已经给你了，将军，去吧。”",
    "“You have the dog's blood. May it do what it must.”": "“狗血你们拿去了。但愿它能破了那法。”",
    "“Bring the blood, brother. We hold the left.”": "“兄长，把血送来。左边的山岭我们守着。”",
    "“Waiting for the gun, sir.”": "“只等炮响，将军。”",
    "“A bucket each, and every man ready.”": "“人人一桶，个个准备好了。”",
    "“Let the paper horses come.”": "“叫那些纸马来吧。”",
    "“Bring the blood, brother. We hold the right.”": "“兄长，把血送来。右边的山岭我们守着。”",
    "The ridge is empty. Nobody has been told to hold it yet.": "山岭上空无一人，还没有人受命来守。",
    "We hold the ridge. The blood is still to come.": "山岭我们守着。血还没送到。",
    "Blood and filth for every paper horse. We wait for the gun.": "纸人纸马，一个也不放过。只等炮响。",
    "A thousand men, and nothing to throw. Hurry, brother.": "一千人在此，手里没东西可泼。哥哥快些。",
    "Let his spirits come. I'll soak every one.": "叫他的鬼兵来吧，我一个个泼透。",
    "The board is quiet.": "棋盘寂静。",
    "Go to the roadside shrine where the glow has begun.": "去路旁那座发光的神龛。",
    "The old shrine at the roadside, dark until now, begins to glow.": "路旁这座暗了的旧神龛，忽然发出微光。",
    "The glow settles. Only the board remains, and a thread of incense.": "微光渐息，只剩棋盘，和一缕香烟。",
    "Defeat Zhang Bao at Yangcheng.": "在阳城击败张宝。",
    "A Yellow Turban tent": "黄巾军的帐篷", "A hermit's shelter": "隐士的草庐", "A prisoner's cart": "囚车",
    "The command tent": "主帅大帐", "Liu Bei's home": "刘备的家", "The Cao family house": "曹家宅院",
    "The Han camp": "汉军营地", "The Yellow Turban line": "黄巾军阵", "The besieged city": "被围的城",
    "The county office": "县衙", "The envoy's rest": "使者歇脚处", "The great mulberry tree": "大桑树", "The travellers' go table": "过客棋桌", "Lu Zhi's tent": "卢植大帐",
    "The great peach tree": "大桃树", "The weiqi board": "围棋盘", "The horse dealers' camp": "马商的营地", "The north gate of Luoyang": "洛阳北门",
    "The notice board": "榜文", "The teahouse": "茶馆", "The village inn": "村店", "Where Zhang Jiao preaches": "张角传道之处",
    "Zhang Bao's sorcery": "张宝的妖术", "The village below the hills": "山下的村子", "The roadside shrine": "路旁的神龛", "The left ridge": "左边的山岭", "The right ridge": "右边的山岭", "Zhang Bao's stronghold": "张宝的城寨", "Zhang Fei's farm": "张飞的庄园",

    "The man that notice will draw out grew up here, in Lousang Village, Zhuo County. His name is Liu Bei.": "这榜文要引出的英雄，就在涿县楼桑村长大。他姓刘，名备。",
    "His uncle, Liu Yuanqi, hears him.": "叔父刘元起听见了。",
    "Armed and mounted at last, the brothers lead their five hundred to the governor.": "兵器鞍马齐备，兄弟三人引着五百乡勇，去见太守。",
    "His lieutenant, Deng Mao, rides out.": "副将邓茂挺枪出马。",
    "Liu Bei marches to relieve the city. But the rebels are too many, and his force is beaten back thirty li.": "玄德引兵前去解围。怎奈贼众势大，救兵寡不敌众，退兵三十里下寨。",
    "Post Guan Yu on the left hill and Zhang Fei on the right.": "让关羽伏于左山，张飞伏于右山。",
    "My teacher Lu Zhi sends me, with a thousand men. How do you stand?": "家师卢中郎遣备引兵一千到此，不知战况如何？",
    "Liu Bei is not the only young man this war will raise. Years before, far to the south in Qiao, lived a boy named Cao Cao.": "这场乱世造就的英雄，不止玄德一人。多年以前，在南方的沛国谯郡，有个少年，名叫曹操。",
    "He loved hunting, music and mischief, and his uncle kept telling his father so.": "他好游猎，喜歌舞，叔父屡次向他父亲告状。",
    "Dong Zhuo looks down on them, and turns his back without a word of thanks. Zhang Fei starts forward, and his brothers hold him back.": "董卓甚是轻视，连谢也不谢，转身便走。张飞大怒，便要上前，被两位兄长拦住。",
    "The armies meet. Zhang Fei spears Zhang Bao's officer Gao Sheng from the saddle — and then Zhang Bao lets down his hair, raises his sword, and chants.": "两军相遇。张飞出马，刺张宝部将高升于马下。张宝随即披发仗剑，作起妖法。",
    "As they fall back, Liu Bei sees a faint glow under the great pine by the road.": "退兵途中，玄德望见路旁大松树下隐隐发光。",
    "Liu Bei marches on Yangcheng with the blood still on his own carts. Again Zhang Bao lets down his hair and chants.": "玄德带着血进兵阳城，血却还在自己车上。张宝又披发仗剑，作起妖法。",
    "The blood is no use down here. It must go up to my brothers on the ridges, left and right.": "血在山下无用，须送上左右山头，交给两位兄弟。",
    "Gather the blood of pigs, sheep and dogs at the farm east of the pine.": "到大松树东边的农庄，讨来猪、羊、狗的血。",
    "Take the blood up to Guan Yu on the left ridge and Zhang Fei on the right.": "把血送上左山岭的关羽和右山岭的张飞。",
    "The farm east of the shrine": "神龛东边的农庄",
    "Join Zhu Jun in the hills, against Zhang Bao.": "到山中与朱儁会合，迎战张宝。",
    "The Rock under the Pine": "松下盘石",
    "The rock under the pine": "松下盘石",
    "Under the great pine by the road, the stones on the flat rock begin to glow.": "路旁大松树下，盘石上的棋子忽然发出微光。",
    "The old men are gone. Only the game remains.": "两位老人已经不见了，只剩下那盘棋。",
    "The farm east of the pine": "大松树东边的农庄",
    "The ridge is empty. Go to the rock under the pine first.": "山岭上空无一人。先去大松树下的盘石。",
    "Go to the rock under the great pine, where the stones have begun to glow.": "到大松树下的盘石那里去，棋子已经发光了。",
}

# Pronunciation fixes for the voice only (the text shown keeps the real
# characters). The speech model guesses some characters with two readings
# wrong; each fix swaps in a homophone with the right reading.
PRON = {
    "长社": "常社", "髯长": "髯常",          # 长 cháng, not zhǎng
    "早降": "早祥",                          # 降 xiáng (surrender), not jiàng
    "缴还": "缴环",                          # 还 huán, not hái
    "刘备为兄": "刘备维兄", "张飞为弟": "张飞维弟", "织席为业": "织席维业", "结为兄弟": "结维兄弟",
    "化为公鸡": "化维公鸡", "挥为两段": "挥维两段", "鸣金为号": "鸣金维号", "诚为可惜": "诚维可惜",
    "称他为": "称他维", "我为天公": "我维天公", "张宝为地公": "张宝维地公", "张梁为人公": "张梁维人公",  # 为 wéi
    "将军": "酱军", "贼将": "贼酱",          # 将 jiàng (general), not jiāng
    "只得了": "只德了", "你得了": "你德了", "得脱": "德脱", "难得者": "难德者",  # 得 dé
    "诈倒": "诈岛", "倒持": "到持",          # 倒 dǎo (fall), dào (upside down)
    "在地": "在弟", "讨地公": "讨弟公",      # 地 dì, not the particle de
}


def spoken(text):
    for a, b in PRON.items():
        text = text.replace(a, b)
    return text

# Who reads what. The narrator (a woman, Kokoro zf_027) reads narration and
# the storyteller's scrolls; every speaking character has his own voice,
# matched by gender and by measured pitch and pace (deep and fast for Zhang
# Fei, slow for Lu Zhi, light for the eunuch Zuo Feng). Recasting a
# character regenerates only his lines.
NARRATOR = "zf_027"
CAST = {
    "liubei": "zm_053", "guanyu": "zm_034", "zhangfei": "zm_029", "caocao": "zm_013",
    "dongzhuo": "zm_098", "zhangbao": "zm_041", "zhangjiao": "zm_068", "luzhi": "zm_081",
    "zhujun": "zm_033", "huangfusong": "zm_055", "chengyuanzhi": "zm_011", "inspector": "zm_096",
    "xushao": "zm_091", "uncle": "zm_014", "zuofeng": "zm_063", "merchant": "zm_025", "immortal": "zm_080",
    "stargrey": "zm_082", "starred": "zm_089",
    "liubei_child": "zf_002", "liuyuanqi": "zm_065",  # the mulberry-tree opening: Liu Bei as a boy, and his uncle  # the two old men at the weiqi board (the Star Lords)
}
# Townsfolk speak in a voice for their kind (tools/tk_places.py "kind").
FOLK_VOICE = {
    "folk.villager": "zm_052", "folk.woman": "zf_022", "folk.elder": "zm_100", "folk.child": "zf_002",
    "folk.lady": "zf_017", "folk.maiden": "zf_023", "folk.girl": "zf_002",
    "folk.monk": "zm_069", "folk.noble": "zm_057", "folk.soldier": "zm_045", "folk.rebel": "zm_016",
    "folk.hunter": "zm_030", "folk.official": "zm_064",
}


# ---- World 2 (tk_story_w2.py) ----
import pathlib as _pl, sys as _sys  # noqa: E402
_sys.path.insert(0, str(_pl.Path(__file__).resolve().parent))
from tk_story_w2 import ZH2 as _ZH2, CAST2 as _CAST2  # noqa: E402
for _k, _v in _ZH2.items():
    ZH.setdefault(_k, _v)
CAST.update(_CAST2)
